/*
** GENERATED by tools/gen-eph-params.py from the parameter table it carries --
** do not edit; regenerate and diff with make check.
**
** The shared parameter index space (EPHEMERIS_PLUGINS_PLAN.md 4.3): one
** index per parameter of every built-in source, all sources in one
** space. us.rgszEphParam[] is indexed by these, and the command-line key
** of a parameter is its source's key, a dot, and its own key ("-bP
** server.url wss://host"). Names are appended and never reordered and never
** reused, so a settings file's meanings survive the table growing.
*/

#ifndef _EPHPARAM_H
#define _EPHPARAM_H

enum {
  epJplFile,               // jpl: file
  epPrometheiaEphemeris,   // prometheia: ephemeris
  epPrometheiaCatalog,     // prometheia: catalog
  epPrometheiaPerturbers,  // prometheia: perturbers
  epServerUrl,             // server: url
  epServerToken,           // server: token
  cEphParam
};

// The rows, in the enum's order. The EPHPARAMROW type that carries them
// and the table's extern are ephem.h's, hand-written: they name EPHPARAM,
// which ephem.h itself defines, and this header is included by astrolog.h
// BEFORE that, because US sizes us.rgszEphParam[] with cEphParam. The macro
// only expands where it is used (ephem.cpp's one definition), so its
// epk* tokens need not exist here.

#define EphParamRowsGenerated() \
  { \
    {"jpl", {"file", "JPL file", epkFile, ""}}, \
    {"prometheia", {"ephemeris", "Ephemeris File", epkFile, ""}}, \
    {"prometheia", {"catalog", "Small-body Catalog", epkFile, ""}}, \
    {"prometheia", {"perturbers", "Perturber Kernel", epkFile, ""}}, \
    {"server", {"url", "Server Address", epkUrl, ""}}, \
    {"server", {"token", "Server Token", epkToken, ""}} \
  }

#endif // _EPHPARAM_H
