// Generated by tools/rc_cmd.py from astrolog.rc -- do not edit.
// Menu label to Windows command id, so an AstroExpression can be
// handed the same number Windows hands it.

typedef struct _RcCmd { CONST char *szLabel; int cmd; } RCCMD;

CONST RCCMD rgcmdQt[] = {
  {"&Open Chart...",               40256},  // cmdOpenChart
  {"Open Chart #&2...",            40257},  // cmdOpenChart2
  {"&Save Chart Info...",          40305},  // cmdSaveChart
  {"Save Chart &Positions...",     40308},  // cmdSavePositions
  {"Save Program Settin&gs...",    40311},  // cmdSaveSettings
  {"Open Charts in &Folder...",    40258},  // cmdOpenDir
  {"Save Chart &List...",          40306},  // cmdSaveList
  {"Save Chart &Exchange...",      40302},  // cmdSaveAAF
  {"Save Chart &Quick*Chart...",   40310},  // cmdSaveQuick
  {"Save Chart i&Calendar...",     40304},  // cmdSaveCalendar
  {"Export Chart &Text Output...", 40313},  // cmdSaveText
  {"Export Chart &Bitmap...",      40303},  // cmdSaveBitmap
  {"Export Chart &Metafile...",    40307},  // cmdSavePicture
  {"Export Chart &PostScript...",  40309},  // cmdSavePS
  {"Export Chart &SVG...",         40312},  // cmdSaveSVG
  {"Export Chart &Wireframe...",   40319},  // cmdSaveWire
  {"&Tile Bitmap",                 40318},  // cmdSaveWallTile
  {"&Center Bitmap",               40314},  // cmdSaveWallCenter
  {"&Stretch Bitmap",              40317},  // cmdSaveWallStretch
  {"&Fit Bitmap",                  40316},  // cmdSaveWallFit
  {"Fi&ll Bitmap",                 40315},  // cmdSaveWallFill
  {"Open Chart &Background...",    40255},  // cmdOpenBackground
  {"Open &World Map...",           40259},  // cmdOpenWorld
  {"&File Settings...",            40335},  // cmdSettingFile
  {"P&rint...",                    40278},  // cmdPrint
  {"Pr&int Setup...",              40279},  // cmdPrintSetup
  {"E&xit",                        40083},  // cmdFileExit
  {"Enter Command &Line...",       40060},  // cmdCommand
  {"Macro &1",                     40154},  // cmdMacro01
  {"Macro &2",                     40155},  // cmdMacro02
  {"Macro &3",                     40156},  // cmdMacro03
  {"Macro &4",                     40157},  // cmdMacro04
  {"Macro &5",                     40158},  // cmdMacro05
  {"Macro &6",                     40159},  // cmdMacro06
  {"Macro &7",                     40160},  // cmdMacro07
  {"Macro &8",                     40161},  // cmdMacro08
  {"Macro &9",                     40162},  // cmdMacro09
  {"Macro 1&0",                    40163},  // cmdMacro10
  {"&Macro 11",                    40164},  // cmdMacro11
  {"M&acro 12",                    40165},  // cmdMacro12
  {"Macro 1&3",                    40166},  // cmdMacro13
  {"Macro 1&4",                    40167},  // cmdMacro14
  {"Macro 1&5",                    40168},  // cmdMacro15
  {"Macro 1&6",                    40169},  // cmdMacro16
  {"Macro 1&7",                    40170},  // cmdMacro17
  {"Macro 1&8",                    40171},  // cmdMacro18
  {"Macro 1&9",                    40172},  // cmdMacro19
  {"Macro 2&0",                    40173},  // cmdMacro20
  {"Macro 2&1",                    40174},  // cmdMacro21
  {"Macro 2&2",                    40175},  // cmdMacro22
  {"&Macro 23",                    40176},  // cmdMacro23
  {"M&acro 24",                    40177},  // cmdMacro24
  {"Macro 2&5",                    40178},  // cmdMacro25
  {"Macro 2&6",                    40179},  // cmdMacro26
  {"Macro 2&7",                    40180},  // cmdMacro27
  {"Macro 2&8",                    40181},  // cmdMacro28
  {"Macro 2&9",                    40182},  // cmdMacro29
  {"Macro 3&0",                    40183},  // cmdMacro30
  {"Macro 3&1",                    40184},  // cmdMacro31
  {"Macro 3&2",                    40185},  // cmdMacro32
  {"Macro 3&3",                    40186},  // cmdMacro33
  {"Macro 3&4",                    40187},  // cmdMacro34
  {"&Macro 35",                    40188},  // cmdMacro35
  {"M&acro 36",                    40189},  // cmdMacro36
  {"Macro 3&7",                    40190},  // cmdMacro37
  {"Macro 3&8",                    40191},  // cmdMacro38
  {"Macro 3&9",                    40192},  // cmdMacro39
  {"Macro 4&0",                    40193},  // cmdMacro40
  {"Macro 4&1",                    40194},  // cmdMacro41
  {"Macro 4&2",                    40195},  // cmdMacro42
  {"Macro 4&3",                    40196},  // cmdMacro43
  {"Macro 4&4",                    40197},  // cmdMacro44
  {"Macro 4&5",                    40198},  // cmdMacro45
  {"Macro 4&6",                    40199},  // cmdMacro46
  {"&Macro 47",                    40200},  // cmdMacro47
  {"M&acro 48",                    40201},  // cmdMacro48
  {"Macro 4&9",                    40202},  // cmdMacro49
  {"Macro 5&0",                    40203},  // cmdMacro50
  {"Macro 5&1",                    40204},  // cmdMacro51
  {"Macro 5&2",                    40205},  // cmdMacro52
  {"Macro 5&3",                    40206},  // cmdMacro53
  {"Macro 5&4",                    40207},  // cmdMacro54
  {"Macro 5&5",                    40208},  // cmdMacro55
  {"Macro 5&6",                    40209},  // cmdMacro56
  {"Macro 5&7",                    40210},  // cmdMacro57
  {"Macro 5&8",                    40211},  // cmdMacro58
  {"&Macro 59",                    40212},  // cmdMacro59
  {"M&acro 60",                    40213},  // cmdMacro60
  {"Macro 6&1",                    40214},  // cmdMacro61
  {"Macro 6&2",                    40215},  // cmdMacro62
  {"Macro 6&3",                    40216},  // cmdMacro63
  {"Macro 6&4",                    40217},  // cmdMacro64
  {"Macro 6&5",                    40218},  // cmdMacro65
  {"Macro 6&6",                    40219},  // cmdMacro66
  {"Macro 6&7",                    40220},  // cmdMacro67
  {"Macro 6&8",                    40221},  // cmdMacro68
  {"Macro 6&9",                    40222},  // cmdMacro69
  {"Macro 7&0",                    40223},  // cmdMacro70
  {"&Macro 71",                    40224},  // cmdMacro71
  {"M&acro 72",                    40225},  // cmdMacro72
  {"Macro 7&3",                    40226},  // cmdMacro73
  {"Macro 7&4",                    40227},  // cmdMacro74
  {"Macro 7&5",                    40228},  // cmdMacro75
  {"Macro 7&6",                    40229},  // cmdMacro76
  {"Macro 7&7",                    40230},  // cmdMacro77
  {"Macro 7&8",                    40231},  // cmdMacro78
  {"Macro 7&9",                    40232},  // cmdMacro79
  {"Macro 8&0",                    40233},  // cmdMacro80
  {"Macro 8&1",                    40234},  // cmdMacro81
  {"Macro 8&2",                    40235},  // cmdMacro82
  {"&Macro 83",                    40236},  // cmdMacro83
  {"M&acro 84",                    40237},  // cmdMacro84
  {"Macro 8&5",                    40238},  // cmdMacro85
  {"Macro 8&6",                    40239},  // cmdMacro86
  {"Macro 8&7",                    40240},  // cmdMacro87
  {"Macro 8&8",                    40241},  // cmdMacro88
  {"Macro 8&9",                    40242},  // cmdMacro89
  {"Macro 9&0",                    40243},  // cmdMacro90
  {"Macro 9&1",                    40244},  // cmdMacro91
  {"Macro 9&2",                    40245},  // cmdMacro92
  {"Macro 9&3",                    40246},  // cmdMacro93
  {"Macro 9&4",                    40247},  // cmdMacro94
  {"&Macro 95",                    40248},  // cmdMacro95
  {"M&acro 96",                    40249},  // cmdMacro96
  {"Copy Chart &Text Output",      40066},  // cmdCopyText
  {"Copy Chart &Bitmap",           40062},  // cmdCopyBitmap
  {"Copy Chart &Metafile",         40063},  // cmdCopyPicture
  {"Copy Chart &PostScript",       40064},  // cmdCopyPS
  {"Copy Chart &SVG",              40065},  // cmdCopySVG
  {"Copy Chart &Wireframe",        40067},  // cmdCopyWire
  {"&Paste",                       40261},  // cmdPaste
  {"Show &Graphics",               40084},  // cmdGraphics
  {"&Buffer Redraws",              40358},  // cmdWinBuffer
  {"&Redraw Screen",               40362},  // cmdWinRedraw
  {"&Clear Screen",                40359},  // cmdWinClear
  {"&Hourglass on Redraw",         40361},  // cmdWinHourglass
  {"Ch&art Resizes Window",        40051},  // cmdChartResizesWindow
  {"&Window Resizes Chart",        40360},  // cmdWindowResizesChart
  {"Si&ze Chart to Window",        40342},  // cmdSizeChartToWindow
  {"&Size Window to Chart",        40344},  // cmdSizeWindowToChart
  {"Size Window &Full Screen",     40343},  // cmdSizeWindowFull
  {"Scroll Page &Up",              40329},  // cmdScrollPageUp
  {"Scroll Page &Down",            40328},  // cmdScrollPageDown
  {"Scroll &to Beginning",         40327},  // cmdScrollHome
  {"Scroll to &End",               40326},  // cmdScrollEnd
  {"&Colored Text",                40059},  // cmdColoredText
  {"&Set Colors...",               40058},  // cmdColor
  {"Show &Interpretations",        40148},  // cmdInterpret
  {"Print &Nearest Second",        40330},  // cmdSecond
  {"&Parallel Aspects",            40260},  // cmdParallel
  {"&Applying Aspects",            40026},  // cmdApplying
  {"Set Chart &Info...",           40331},  // cmdSetInfo
  {"Chart for &Now",               40251},  // cmdNow
  {"D&efault Chart Info...",       40070},  // cmdDefaultInfo
  {"Set Chart #&2 Info...",        40332},  // cmdSetInfo2
  {"Charts #&3 Through #6...",     40333},  // cmdSetInfoAll
  {"&Chart List...",               40149},  // cmdList
  {"&Previous Chart",              40153},  // cmdListPrev
  {"&Next Chart",                  40152},  // cmdListNext
  {"&First Chart",                 40150},  // cmdListFirst
  {"&Last Chart",                  40151},  // cmdListLast
  {"Swap Chart #&1 and #2",        40349},  // cmdSwap12
  {"No &Relationship Chart",       40287},  // cmdRelNo
  {"Com&parison Chart",            40283},  // cmdRelComparison
  {"&Synastry Chart",              40289},  // cmdRelSynastry
  {"&Composite Chart",             40284},  // cmdRelComposite
  {"Time Space &Midpoint Chart",   40286},  // cmdRelMidpoint
  {"Date &Difference Chart",       40285},  // cmdRelDate
  {"&Biorhythm Chart",             40282},  // cmdRelBiorhythm
  {"&Transit and Natal",           40290},  // cmdRelTransit
  {"&Progressed and Natal",        40288},  // cmdRelProgressed
  {"&Sidereal Zodiac",             40341},  // cmdSidereal
  {"He&liocentric",                40104},  // cmdHeliocentric
  {"&Placidus",                    40117},  // cmdHouse00
  {"&Koch",                        40118},  // cmdHouse01
  {"&Campanus",                    40120},  // cmdHouse03
  {"&Regiomontanus",               40122},  // cmdHouse05
  {"&Topocentric",                 40125},  // cmdHouse08
  {"Alca&bitius",                  40126},  // cmdHouse09
  {"Kr&usinski",                   40127},  // cmdHouse10
  {"A&.P.C.",                      40135},  // cmdHouse18
  {"Savard-&A",                    40138},  // cmdHouse21
  {"Porph&yry",                    40123},  // cmdHouse06
  {"Pullen (S.Rati&o)",            40129},  // cmdHouse12
  {"Pullen (S.&Delta)",            40130},  // cmdHouse13
  {"&Meridian",                    40121},  // cmdHouse04
  {"Morinu&s",                     40124},  // cmdHouse07
  {"Hori&zon",                     40134},  // cmdHouse17
  {"Carter& P.Equat.",             40136},  // cmdHouse19
  {"Suns&hine",                    40137},  // cmdHouse20
  {"Sr&ipati",                     40133},  // cmdHouse16
  {"&Equal",                       40119},  // cmdHouse02
  {"E&qual (MC)",                  40128},  // cmdHouse11
  {"&Whole",                       40131},  // cmdHouse14
  {"&Vedic",                       40132},  // cmdHouse15
  {"&Null",                        40139},  // cmdHouse22
  {"&Solar Chart",                 40147},  // cmdHouseSetSolar
  {"&3D Houses",                   40140},  // cmdHouseSet3D
  {"Show &Decans",                 40141},  // cmdHouseSetDecan
  {"Show D&wads",                  40142},  // cmdHouseSetDwad
  {"&Flip Signs with Houses",      40143},  // cmdHouseSetFlip
  {"&Geodetic Houses",             40144},  // cmdHouseSetGeodetic
  {"&Indian Wheel Order",          40145},  // cmdHouseSetIndian
  {"Show &Navamsas",               40146},  // cmdHouseSetNavamsa
  {"&Aspect Settings...",          40027},  // cmdAspect
  {"&Object Settings...",          40252},  // cmdObject
  {"More Ob&ject Settings...",     40253},  // cmdObject2
  {"Object Selectio&ns...",        40365},  // cmdObjectSel
  {"&Restrictions...",             40291},  // cmdRes
  {"Star Restr&ictions...",        40345},  // cmdStar
  {"&Transit Restrictions...",     40298},  // cmdResTransit
  {"&Moons Chart",                 40048},  // cmdChartMoons
  {"&Exoplanets Chart",            40034},  // cmdChartExo
  {"Moon &Restrictions...",        40250},  // cmdMoons
  {"Moon &Object Settings...",     40254},  // cmdObjectM
  {"&Include Moons",               40296},  // cmdResMoons
  {"Include &Body Centers (COB)",  40292},  // cmdResCOB
  {"Object &Customization...",     40068},  // cmdCustom
  {"&Star Customization...",       40069},  // cmdCustomS
  {"Include &Minors",              40295},  // cmdResMinor
  {"Include &Cusps",               40293},  // cmdResCusp
  {"Include &Uranians",            40299},  // cmdResUranian
  {"Include D&warfs",              40294},  // cmdResDwarf
  {"Include &Fixed Stars",         40297},  // cmdResStar
  {"Calculation Settin&gs...",     40334},  // cmdSettingCalc
  {"&Display Settings...",         40071},  // cmdDisplay
  {"Standard Radi&x",              40043},  // cmdChartList
  {"House &Wheel",                 40057},  // cmdChartWheel
  {"Aspect Midpoint &Grid",        40036},  // cmdChartGrid
  {"&Aspect List",                 40029},  // cmdChartAspect
  {"&Midpoint List",               40046},  // cmdChartMidpoint
  {"Local Hori&zon",               40037},  // cmdChartHorizon
  {"Solar System &Orbit",          40049},  // cmdChartOrbit
  {"Ga&uquelin Sectors",           40053},  // cmdChartSector
  {"&Calendar",                    40031},  // cmdChartCalendar
  {"Inf&luence",                   40042},  // cmdChartInfluence
  {"Esoter&ic",                    40033},  // cmdChartEsoteric
  {"Astrocartograp&hy",            40030},  // cmdChartAstroGraph
  {"&Ephemeris",                   40032},  // cmdChartEphemeris
  {"Ara&bic Parts",                40028},  // cmdChartArabic
  {"Risi&ng and Setting",          40052},  // cmdChartRising
  {"Nea&rest Cities",              40044},  // cmdChartLocal
  {"&Transits...",                 40356},  // cmdTransit
  {"&Progressions...",             40280},  // cmdProgress
  {"Chart &Settings...",           40054},  // cmdChartSettings
  {"Draw Chart Sp&here",           40055},  // cmdChartSphere
  {"Draw &World Map",              40045},  // cmdChartMap
  {"Draw &Globe",                  40035},  // cmdChartGlobe
  {"Draw &Polar Globe",            40050},  // cmdChartPolar
  {"Draw &Telescope",              40056},  // cmdChartTelescope
  {"&Reverse Background",          40098},  // cmdGraphicsReverse
  {"&Monochrome",                  40097},  // cmdGraphicsMonochrome
  {"S&quare Screen",               40100},  // cmdGraphicsSquare
  {"&Small",                       40320},  // cmdScale1
  {"&Medium",                      40321},  // cmdScale2
  {"&Large",                       40322},  // cmdScale3
  {"&Huge",                        40323},  // cmdScale4
  {"&Decrease",                    40324},  // cmdScaleDecrease
  {"&Increase",                    40325},  // cmdScaleIncrease
  {"D&ecrease Text",               40350},  // cmdTextDecrease
  {"I&ncrease Text",               40351},  // cmdTextIncrease
  {"Show &Border",                 40090},  // cmdGraphicsBorder
  {"Show Chart &Info",             40102},  // cmdGraphicsText
  {"Show Info &Sidebar",           40099},  // cmdGraphicsSidebar
  {"&Thicker Lines",               40103},  // cmdGraphicsThick
  {"&Antialias Lines",             40086},  // cmdGraphicsAntialias
  {"Show Glyph &Labels",           40095},  // cmdGraphicsLabel
  {"Show &Glyphs on Aspect Lines", 40087},  // cmdGraphicsAspect
  {"Show &Constellations",         40061},  // cmdConstellation
  {"Show Full &Star List",         40085},  // cmdGraphicsAllStar
  {"Show E&xoplanets",             40093},  // cmdGraphicsExo
  {"Show Constellation &Lines",    40101},  // cmdGraphicsStarLine
  {"Show &House Details",          40094},  // cmdGraphicsHouse
  {"Show &Equator",                40092},  // cmdGraphicsEquator
  {"Show C&ities",                 40091},  // cmdGraphicsCity
  {"Use Detailed World &Map",      40089},  // cmdGraphicsBmp
  {"Use Ecliptic &Axis",           40088},  // cmdGraphicsAxis
  {"Rotate &West",                 40301},  // cmdRotateWest
  {"Rotate &East",                 40300},  // cmdRotateEast
  {"Tilt &North",                  40352},  // cmdTiltNorth
  {"Tilt &South",                  40353},  // cmdTiltSouth
  {"Set Tilt to &Zero",            40354},  // cmdTiltZero
  {"Zoom &Out",                    40364},  // cmdZoomOut
  {"Zoom &In",                     40363},  // cmdZoomIn
  {"Show &Indian Wheels",          40038},  // cmdChartIndian
  {"Draw &South Indian",           40041},  // cmdChartIndianS
  {"Draw &North Indian",           40040},  // cmdChartIndianN
  {"Draw &East Indian",            40039},  // cmdChartIndianE
  {"Modify &Display",              40096},  // cmdGraphicsModify
  {"Modif&y Chart",                40047},  // cmdChartModify
  {"Blac&k",                       40262},  // cmdPen00
  {"&White",                       40277},  // cmdPen15
  {"&Red",                         40271},  // cmdPen09
  {"&Green",                       40272},  // cmdPen10
  {"&Blue",                        40274},  // cmdPen12
  {"&Yellow",                      40273},  // cmdPen11
  {"&Magenta",                     40275},  // cmdPen13
  {"&Cyan",                        40276},  // cmdPen14
  {"Gr&ay",                        40270},  // cmdPen08
  {"&Lt. Gray",                    40269},  // cmdPen07
  {"Maroo&n",                      40263},  // cmdPen01
  {"Dk. Gr&een",                   40264},  // cmdPen02
  {"Dk. Bl&ue",                    40266},  // cmdPen04
  {"Mai&ze",                       40265},  // cmdPen03
  {"&Purple",                      40267},  // cmdPen05
  {"&Dk. Cyan",                    40268},  // cmdPen06
  {"&Graphics Settings...",        40336},  // cmdSettingGraphics
  {"Do &Animation",                40010},  // cmdAnimateNo
  {"Update to &Now",               40020},  // cmdAnimateNow
  {"&Seconds",                     40011},  // cmdAnimateNo1
  {"&Minutes",                     40012},  // cmdAnimateNo2
  {"&Hours",                       40013},  // cmdAnimateNo3
  {"&Days",                        40014},  // cmdAnimateNo4
  {"M&onths",                      40015},  // cmdAnimateNo5
  {"&Years",                       40016},  // cmdAnimateNo6
  {"&Decades",                     40017},  // cmdAnimateNo7
  {"&Centuries",                   40018},  // cmdAnimateNo8
  {"Mi&llennia",                   40019},  // cmdAnimateNo9
  {"1/&10th Seconds",              40021},  // cmdAnimateNo_11
  {"1/1&00th Seconds",             40022},  // cmdAnimateNo_12
  {"1&/1000th Seconds",            40023},  // cmdAnimateNo_13
  {"&One Unit",                    40001},  // cmdAnimateF1
  {"&Two Units",                   40002},  // cmdAnimateF2
  {"T&hree Units",                 40003},  // cmdAnimateF3
  {"&Four Units",                  40004},  // cmdAnimateF4
  {"Fi&ve Units",                  40005},  // cmdAnimateF5
  {"Si&x Units",                   40006},  // cmdAnimateF6
  {"&Seven Units",                 40007},  // cmdAnimateF7
  {"&Eight Units",                 40008},  // cmdAnimateF8
  {"&Nine Units",                  40009},  // cmdAnimateF9
  {"&Reverse Direction",           40025},  // cmdAnimateReverse
  {"&Pause Animation",             40024},  // cmdAnimatePause
  {"&Timed Exposure",              40355},  // cmdTimedExposure
  {"Step &Forward",                40347},  // cmdStepForward
  {"Step &Backward",               40346},  // cmdStepBackward
  {"&Store Chart Info",            40348},  // cmdStore
  {"Re&call Chart Info",           40281},  // cmdRecall
  {"Open &Documentation",          40075},  // cmdDocHelpfile
  {"&Open Documentation",          40075},  // cmdDocHelpfile
  {"Open &Changes",                40080},  // cmdDocUpdate
  {"Open &License",                40076},  // cmdDocLicense
  {"Open &Website",                40081},  // cmdDocWebsite
  {"Open Website &Mirror",         40082},  // cmdDocWebsite2
  {"Open &Default Settings",       40073},  // cmdDocDefault
  {"Open &Atlas",                  40072},  // cmdDocAtlas
  {"Open &Time Zone Changes",      40079},  // cmdDocTimezone
  {"Open &Star List",              40078},  // cmdDocStar
  {"Open &Orbital Elements",       40077},  // cmdDocOrbit
  {"Open &Exoplanet List",         40074},  // cmdDocExo
  {"List Si&gns",                  40115},  // cmdHelpSign
  {"List &Objects",                40111},  // cmdHelpObject
  {"List Aspec&ts",                40106},  // cmdHelpAspect
  {"List &Constellations",         40107},  // cmdHelpConstellation
  {"List &Planet Info",            40113},  // cmdHelpPlanetInfo
  {"List &Rays",                   40114},  // cmdHelpRay
  {"List &General Meanings",       40110},  // cmdHelpMeaning
  {"List S&witches",               40116},  // cmdHelpSwitch
  {"List O&bscure Switches",       40112},  // cmdHelpObscure
  {"List &Keystrokes",             40109},  // cmdHelpKeystroke
  {"List Cr&edits",                40108},  // cmdHelpCredit
  {"Create Program Group (&User)", 40340},  // cmdSetupUser
  {"Create Program Group (&All)",  40337},  // cmdSetupAll
  {"Create &Desktop Icon",         40338},  // cmdSetupDesktop
  {"Install File &Extensions",     40339},  // cmdSetupExtension
  {"Uninstall File E&xtensions",   40357},  // cmdUnsetup
  {"&About Astrolog...",           40105},  // cmdHelpAbout
};
CONST int ccmdQt = 366;
