// Ephemeris protocol version 4: the byte-level codec.
//
// EPHEMERIS_PLUGINS_PLAN.md section 3 is the specification this implements;
// every rule below cites its subsection. Version 4 is source-neutral --
// bodies are NAIF/SPK-IDs with typed extras, options are explicit fields in
// per-object profiles, instants are two-part Julian dates -- so any engine
// can serve it without a map from Swiss Ephemeris numbering (the reason for
// the break from version 3, ephproto.h).
//
// Compiled into both ends, header-only, no dependencies beyond the standard
// library. Everything moves through the explicit little-endian Writer and
// Reader; nothing is ever cast onto wire bytes. Parsers are canonical: they
// REFUSE input a conforming encoder could not have produced (3.1), because
// the result cache keys on the question block's bytes (3.7) and two
// spellings of one question would be two cache entries and two answers.
//
// Outcomes: kOk; kMalformed (the peer broke a rule: ERROR 1); kUnsupported
// (a registry value or critical extension this end does not implement:
// ERROR 11 -- registries grow, so an unknown value is not a broken peer).
// Where both apply, malformed wins.
//
// ephsrv/conformance/ holds the fixtures that pin this codec to the
// specification, generated by tools/ephproto4-fixtures.py from the spec
// text alone; ephsrv/ephproto4_test.cpp runs them.

#ifndef EPHPROTO4_H
#define EPHPROTO4_H

#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <string>
#include <vector>

namespace eph4 {

// ---- 3.2, A.1 envelope and message types ------------------------------------

inline constexpr uint16_t kMagic = 0x1EF0;
inline constexpr uint8_t kProtoVersion = 4;
inline constexpr uint8_t kProtoMin = 4;
inline constexpr uint16_t kDefaultPort = 47190;
inline constexpr size_t kEnvelopeSize = 16;
inline constexpr uint8_t kEnvFlagZstd = 0x01;
// Before WELCOME a peer's messages are bounded by this, not maxPayload.
inline constexpr uint32_t kPreSessionMaxPayload = 64 * 1024;

enum MsgType : uint16_t {
  kMsgHello = 1, kMsgWelcome = 2, kMsgRequest = 3, kMsgData = 4,
  kMsgError = 5, kMsgPing = 6, kMsgPong = 7, kMsgCancel = 8,
  kMsgLookup = 9, kMsgLookupResult = 10, kMsgSegData = 15,
};

// A.2 caps bits.
inline constexpr uint32_t kCapF32 = 1u << 0;
inline constexpr uint32_t kCapZstd = 1u << 1;
inline constexpr uint32_t kCapCancel = 1u << 2;
inline constexpr uint32_t kCapLookup = 1u << 3;
inline constexpr uint32_t kCapInstantLists = 1u << 4;
inline constexpr uint32_t kCapPriority = 1u << 5;
inline constexpr uint32_t kCapSegments = 1u << 6;
inline constexpr uint32_t kCapDesignations = 1u << 7;

// A.5-A.16 registries: the largest value each field has today. A value past
// it is kUnsupported, never kMalformed (3.1).
enum Observer : uint8_t { kObsGeo = 0, kObsTopo = 1, kObsHelio = 2, kObsBary = 3, kObsBody = 4 };
inline constexpr uint8_t kObserverMax = 4;
enum Plane : uint8_t { kPlaneEcliptic = 0, kPlaneEquator = 1 };
enum Form : uint8_t { kFormSpherical = 0, kFormRectangular = 1 };
enum Frame : uint8_t { kFrameTrueOfDate = 0, kFrameMeanOfDate = 1, kFrameJ2000 = 2, kFrameIcrf = 3 };
inline constexpr uint8_t kFrameMax = 3;
inline constexpr uint8_t kCorrLightTime = 1, kCorrDeflection = 2, kCorrAberration = 4;
inline constexpr uint8_t kCorrMask = 7;
enum SiderealPlane : uint8_t { kSidPlaneDate = 0, kSidPlaneAnchor = 1, kSidPlaneInvariable = 2 };
inline constexpr uint8_t kSidPlaneMax = 2;
enum TimeScale : uint8_t { kTimeUT1 = 0, kTimeTT = 1, kTimeTDB = 2 };
inline constexpr uint8_t kTimeScaleMax = 2;
enum TimeMode : uint8_t { kTimeGrid = 0, kTimeList = 1 };
inline constexpr uint32_t kColSigma = 1u << 0, kColAyanamsa = 1u << 1,
                          kColLightTime = 1u << 2, kColDeltaT = 1u << 3;
inline constexpr uint32_t kColMask = 0xF;
enum ObjKind : uint8_t {
  kObjBody = 0, kObjOrbitPoint = 1, kObjStar = 2, kObjHypothetical = 3,
  kObjElements = 4, kObjDesignation = 5,
};
inline constexpr uint8_t kObjKindMax = 5;
enum OrbitPoint : uint8_t { kPtAscNode = 0, kPtDescNode = 1, kPtPeri = 2, kPtApo = 3 };
inline constexpr uint8_t kOrbitPointMax = 3;
enum OrbitMethod : uint8_t {
  kMethMean = 0, kMethOsculating = 1, kMethInterpolated = 2, kMethOscuBary = 3,
  kMethFocal = 4,
};
inline constexpr uint8_t kOrbitMethodMax = 4;
enum Equinox : uint8_t { kEqJ2000 = 0, kEqB1950 = 1, kEqJ1900 = 2, kEqOfDate = 3, kEqExplicit = 4 };
inline constexpr uint8_t kEquinoxMax = 4;
inline constexpr uint8_t kCentreMax = 1;   // 0 Sun, 1 Earth
enum Precision : uint8_t { kPrecF64 = 0, kPrecF32 = 1 };

// A.17 per-object and A.19 whole-request error codes.
enum ObjErr : uint16_t {
  kOErrNone = 0, kOErrUnknownBody = 1, kOErrUnsupported = 2, kOErrCoverage = 3,
  kOErrDataMissing = 4, kOErrUndefinedPoint = 5, kOErrAmbiguous = 6,
  kOErrNumerical = 7, kOErrInternal = 8,
};
enum ErrCode : uint16_t {
  kErrMalformed = 1, kErrLimits = 2, kErrUnknownType = 3, kErrInternal = 4,
  kErrSource = 5, kErrRateLimited = 6, kErrToken = 7, kErrVersion = 8,
  kErrBusy = 9, kErrCancelled = 10, kErrUnsupported = 11, kErrDraining = 12,
};
inline constexpr uint16_t kErrFlagClosing = 1, kErrFlagRetryable = 2;
// A.18 META flags.
inline constexpr uint8_t kMetaApproximated = 1, kMetaExtrapolated = 2,
                         kMetaHasSigma = 4, kMetaPartial = 8, kMetaNoSpeeds = 16;
// DATA and SEGDATA chunk flags.
inline constexpr uint8_t kChunkLast = 1, kChunkIgnoredExt = 2, kChunkMeta = 4;

inline constexpr int32_t kNaifNone = INT32_MIN;          // META resolvedNaif
inline constexpr uint32_t kRowNone = 0xFFFFFFFFu;        // META firstFailedRow
inline constexpr uint8_t kSourceNone = 0xFF;             // META sourceIdx
inline constexpr size_t kTokenMax = 128;
inline constexpr double kJdAbsMax = 1e8;
inline constexpr uint8_t kSegDegreeMax = 31;
inline constexpr int64_t kNsPerDay = 86400LL * 1000000000LL;

// TLV tags (A.3, A.4). Bit 15 is critical.
inline constexpr uint16_t kTagCritical = 0x8000;
enum WelcomeTag : uint16_t {
  kCapTagKinds = 0x0001, kCapTagObservers = 0x0002, kCapTagPlanesFormsFrames = 0x0003,
  kCapTagCorrections = 0x0004, kCapTagOrbit = 0x0005, kCapTagColumns = 0x0006,
  kCapTagZodiacs = 0x0007, kCapTagSiderealPlanes = 0x0008, kCapTagTimeScales = 0x0009,
  kCapTagCoverage = 0x000A, kCapTagCatalogs = 0x000B, kCapTagDeltaT = 0x000C,
  kCapTagPrecession = 0x000D, kCapTagRate = 0x000E, kCapTagSegments = 0x000F,
  kCapTagLookup = 0x0010, kCapTagHypotheticals = 0x0011, kCapTagEquinoxes = 0x0012,
};
enum RequestTag : uint16_t {
  kReqTagPrecession = 0x0003, kReqTagEphemerisPin = 0x8001, kReqTagCatalogPin = 0x8002,
};

// The canonical quiet NaN, the one NaN the protocol allows (deltaTSec).
inline double CanonicalNaN() {
  uint64_t u = 0x7FF8000000000000ull;
  double d;
  memcpy(&d, &u, 8);
  return d;
}
inline bool IsCanonicalNaN(double d) {
  uint64_t u;
  memcpy(&u, &d, 8);
  return u == 0x7FF8000000000000ull;
}

// A.11 zodiac tokens: the Swiss Ephemeris 2.10.03 SE_SIDM_* order, then
// "user". Index = the Swiss mode number for the first 47.
inline constexpr const char *kZodiacTokens[] = {
  "fagan-bradley", "lahiri", "deluce", "raman", "usha-shashi", "krishnamurti",
  "djwhal-khul", "yukteshwar", "jn-bhasin", "babyl-kugler1", "babyl-kugler2",
  "babyl-kugler3", "babyl-huber", "babyl-etpsc", "aldebaran-15tau",
  "hipparchos", "sassanian", "galcent-0sag", "j2000", "j1900", "b1950",
  "suryasiddhanta", "suryasiddhanta-msun", "aryabhata", "aryabhata-msun",
  "ss-revati", "ss-citra", "true-citra", "true-revati", "true-pushya",
  "galcent-rgilbrand", "galequ-iau1958", "galequ-true", "galequ-mula",
  "galalign-mardyks", "true-mula", "galcent-mula-wilhelm", "aryabhata-522",
  "babyl-britton", "true-sheoran", "galcent-cochrane", "galequ-fiorenza",
  "valens-moon", "lahiri-1940", "lahiri-vp285", "krishnamurti-vp291",
  "lahiri-icrc", "user",
};
inline constexpr int kZodiacTokenCount = (int)(sizeof(kZodiacTokens) / sizeof(kZodiacTokens[0]));
inline int ZodiacIndex(const std::string &s) {
  for (int i = 0; i < kZodiacTokenCount; i++)
    if (s == kZodiacTokens[i]) return i;
  return -1;
}
inline bool ZodiacIsUser(const std::string &s) { return s == "user"; }

// A.15 named hypotheticals, in seorbel.txt order (index + 1 = entry number).
inline constexpr const char *kHypotheticalTokens[] = {
  "cupido", "hades", "zeus", "kronos", "apollon", "admetos", "vulcanus",
  "poseidon", "isis-transpluto", "nibiru", "harrington", "neptune-leverrier",
  "neptune-adams", "pluto-lowell", "pluto-pickering", "vulcan", "white-moon",
  "proserpina", "waldemath",
};
inline constexpr int kHypotheticalTokenCount =
  (int)(sizeof(kHypotheticalTokens) / sizeof(kHypotheticalTokens[0]));

// ---- 3.1 primitives ------------------------------------------------------------

enum Outcome : int { kOk = 0, kMalformed = 1, kUnsupported = 11 };

class Writer {
public:
  explicit Writer(std::vector<uint8_t> *out) : out_(out) {}
  void u8(uint8_t v) { out_->push_back(v); }
  void u16(uint16_t v) { for (int i = 0; i < 2; i++) out_->push_back((uint8_t)(v >> (8 * i))); }
  void u32(uint32_t v) { for (int i = 0; i < 4; i++) out_->push_back((uint8_t)(v >> (8 * i))); }
  void u64(uint64_t v) { for (int i = 0; i < 8; i++) out_->push_back((uint8_t)(v >> (8 * i))); }
  void i32(int32_t v) { u32((uint32_t)v); }
  void i64(int64_t v) { u64((uint64_t)v); }
  void f32(float v) { uint32_t u; memcpy(&u, &v, 4); u32(u); }
  void f64(double v) { uint64_t u; memcpy(&u, &v, 8); u64(u); }
  void raw(const void *p, size_t n) {
    const uint8_t *b = (const uint8_t *)p;
    out_->insert(out_->end(), b, b + n);
  }
  // str8: the caller guarantees <= 255 bytes (encoders validate first).
  void str8(const std::string &s) { u8((uint8_t)s.size()); raw(s.data(), s.size()); }
  size_t size() const { return out_->size(); }
  void patchU16(size_t at, uint16_t v) { (*out_)[at] = (uint8_t)v; (*out_)[at + 1] = (uint8_t)(v >> 8); }
  void patchU32(size_t at, uint32_t v) {
    for (int i = 0; i < 4; i++) (*out_)[at + i] = (uint8_t)(v >> (8 * i));
  }
private:
  std::vector<uint8_t> *out_;
};

// Reads latch a failure on truncation and return zeros after it; callers
// check ok() once per structure. Semantic problems are recorded with
// Malformed()/Unsupported() and the parse continues where it can, so the
// first-found malformed rule wins over an unsupported value seen earlier.
class Reader {
public:
  Reader(const uint8_t *p, size_t n) : p_(p), n_(n) {}
  bool ok() const { return !trunc_; }
  size_t left() const { return n_ - pos_; }
  uint8_t u8() { return need(1) ? p_[pos_++] : 0; }
  uint16_t u16() {
    if (!need(2)) return 0;
    uint16_t v = (uint16_t)(p_[pos_] | (p_[pos_ + 1] << 8));
    pos_ += 2;
    return v;
  }
  uint32_t u32() {
    if (!need(4)) return 0;
    uint32_t v = 0;
    for (int i = 3; i >= 0; i--) v = (v << 8) | p_[pos_ + i];
    pos_ += 4;
    return v;
  }
  uint64_t u64() {
    if (!need(8)) return 0;
    uint64_t v = 0;
    for (int i = 7; i >= 0; i--) v = (v << 8) | p_[pos_ + i];
    pos_ += 8;
    return v;
  }
  int32_t i32() { return (int32_t)u32(); }
  int64_t i64() { return (int64_t)u64(); }
  float f32() { uint32_t u = u32(); float f; memcpy(&f, &u, 4); return f; }
  double f64() { uint64_t u = u64(); double d; memcpy(&d, &u, 8); return d; }
  const uint8_t *bytes(size_t n) {
    if (!need(n)) return nullptr;
    const uint8_t *b = p_ + pos_;
    pos_ += n;
    return b;
  }
  std::string str8() {
    uint8_t n = u8();
    const uint8_t *b = bytes(n);
    return b ? std::string((const char *)b, n) : std::string();
  }
private:
  bool need(size_t n) {
    if (trunc_ || n > n_ - pos_) { trunc_ = true; pos_ = n_; return false; }
    return true;
  }
  const uint8_t *p_;
  size_t n_;
  size_t pos_ = 0;
  bool trunc_ = false;
};

// Collects a parse's verdict: malformed wins over unsupported.
class Verdict {
public:
  void Malformed(const char *why) { if (!mal_) { mal_ = true; why_ = why; } }
  void Unsupported(const char *why) { if (!mal_ && !uns_) { uns_ = true; why_ = why; } }
  Outcome outcome() const { return mal_ ? kMalformed : uns_ ? kUnsupported : kOk; }
  const std::string &why() const { return why_; }
  bool malformed() const { return mal_; }
  bool unsupported() const { return uns_; }
private:
  bool mal_ = false, uns_ = false;
  std::string why_;
};

// 3.1 str8 content: valid UTF-8, no C0 control characters.
inline bool ValidText(const std::string &s) {
  const unsigned char *p = (const unsigned char *)s.data();
  size_t n = s.size(), i = 0;
  while (i < n) {
    unsigned char c = p[i];
    if (c < 0x20) return false;
    if (c < 0x80) { i++; continue; }
    int len;
    uint32_t cp;
    if ((c & 0xE0) == 0xC0) { len = 2; cp = c & 0x1F; }
    else if ((c & 0xF0) == 0xE0) { len = 3; cp = c & 0x0F; }
    else if ((c & 0xF8) == 0xF0) { len = 4; cp = c & 0x07; }
    else return false;
    if (i + (size_t)len > n) return false;
    for (int k = 1; k < len; k++) {
      if ((p[i + k] & 0xC0) != 0x80) return false;
      cp = (cp << 6) | (p[i + k] & 0x3F);
    }
    // Overlong forms, surrogates and past U+10FFFF are not UTF-8.
    if ((len == 2 && cp < 0x80) || (len == 3 && cp < 0x800) || (len == 4 && cp < 0x10000) ||
        (cp >= 0xD800 && cp <= 0xDFFF) || cp > 0x10FFFF)
      return false;
    i += (size_t)len;
  }
  return true;
}

// ---- 3.1 TIME and TLV --------------------------------------------------------

struct Time {
  double jd1 = 0.0, jd2 = 0.0;
  bool IsZero() const { return jd1 == 0.0 && jd2 == 0.0; }
  double Sum() const { return jd1 + jd2; }
};
inline bool operator==(const Time &a, const Time &b) { return a.jd1 == b.jd1 && a.jd2 == b.jd2; }

inline Time ReadTime(Reader &r, Verdict &v) {
  Time t;
  t.jd1 = r.f64();
  t.jd2 = r.f64();
  if (!std::isfinite(t.jd1) || !std::isfinite(t.jd2) ||
      std::fabs(t.jd1) + std::fabs(t.jd2) > kJdAbsMax)
    v.Malformed("TIME not finite or outside |jd| <= 1e8");
  return t;
}
inline void WriteTime(Writer &w, const Time &t) { w.f64(t.jd1); w.f64(t.jd2); }

inline std::string ReadText(Reader &r, Verdict &v, const char *what) {
  std::string s = r.str8();
  if (r.ok() && !ValidText(s)) v.Malformed(what);
  return s;
}

struct Tlv {
  uint16_t tag = 0;
  std::string value;   // the payload bytes
};
using TlvList = std::vector<Tlv>;

// knownTags: the tags this message type assigns (NULL-free array). An
// unknown critical tag is unsupported; an unknown non-critical tag is kept
// and flagged via *pfIgnored.
inline TlvList ReadTlv(Reader &r, Verdict &v, const uint16_t *known, size_t cKnown,
                       bool *pfIgnored = nullptr) {
  TlvList out;
  uint16_t total = r.u16();
  const uint8_t *area = r.bytes(total);
  if (!r.ok()) return out;
  Reader t(area, total);
  int prev = -1;
  while (t.left() > 0) {
    Tlv e;
    e.tag = t.u16();
    uint16_t len = t.u16();
    const uint8_t *p = t.bytes(len);
    if (!t.ok()) { v.Malformed("TLV entry runs past its area"); return out; }
    if ((int)e.tag <= prev) v.Malformed("TLV tags not strictly ascending");
    prev = e.tag;
    e.value.assign((const char *)p, len);
    bool fKnown = false;
    for (size_t i = 0; i < cKnown; i++)
      if (known[i] == e.tag) fKnown = true;
    if (!fKnown) {
      if (e.tag & kTagCritical) v.Unsupported("unknown critical extension");
      else if (pfIgnored) *pfIgnored = true;
    }
    out.push_back(std::move(e));
  }
  return out;
}
inline void WriteTlv(Writer &w, const TlvList &list) {
  size_t at = w.size();
  w.u16(0);
  size_t start = w.size();
  for (const Tlv &e : list) {
    w.u16(e.tag);
    w.u16((uint16_t)e.value.size());
    w.raw(e.value.data(), e.value.size());
  }
  w.patchU16(at, (uint16_t)(w.size() - start));
}
// A TLV payload that is exactly one str8 (the REQUEST pins, a precession model).
inline bool TlvStr8(const Tlv &e, std::string *out) {
  if (e.value.empty() || (uint8_t)e.value[0] + 1u != e.value.size()) return false;
  *out = e.value.substr(1);
  return ValidText(*out);
}

// ---- 3.2 envelope ----------------------------------------------------------------

struct Envelope {
  uint8_t version = kProtoVersion;
  uint8_t flags = 0;
  uint16_t type = 0;
  uint32_t requestId = 0;
  uint32_t payloadLen = 0;
};

inline void WriteEnvelope(std::vector<uint8_t> *out, uint16_t type, uint32_t requestId,
                          size_t payloadLen, uint8_t version = kProtoVersion,
                          uint8_t flags = 0) {
  Writer w(out);
  w.u16(kMagic); w.u8(version); w.u8(flags); w.u16(type); w.u16(0);
  w.u32(requestId); w.u32((uint32_t)payloadLen);
}

// Structure only: magic, reserved, flag bits, and that the payload length
// matches the bytes present. Versions are the session's business (3.3):
// a version < 4 is an older client owed a legacy ERROR 8.
inline Outcome ParseEnvelope(const uint8_t *p, size_t n, Envelope *e, std::string *why) {
  if (n < kEnvelopeSize) { *why = "shorter than the envelope"; return kMalformed; }
  Reader r(p, kEnvelopeSize);
  if (r.u16() != kMagic) { *why = "bad magic"; return kMalformed; }
  e->version = r.u8();
  e->flags = r.u8();
  e->type = r.u16();
  uint16_t reserved = r.u16();
  e->requestId = r.u32();
  e->payloadLen = r.u32();
  if (reserved != 0) { *why = "envelope reserved field nonzero"; return kMalformed; }
  if (e->version >= kProtoMin && (e->flags & ~kEnvFlagZstd)) {
    *why = "unknown envelope flag bits";
    return kMalformed;
  }
  if ((size_t)e->payloadLen != n - kEnvelopeSize) {
    *why = "payload length does not match the frame";
    return kMalformed;
  }
  return kOk;
}

// 3.2: which messages carry a request id, which carry 0, which either.
inline Outcome CheckRequestId(const Envelope &e, std::string *why) {
  switch (e.type) {
    case kMsgHello: case kMsgWelcome:
      if (e.requestId != 0) { *why = "HELLO/WELCOME with a nonzero requestId"; return kMalformed; }
      break;
    case kMsgRequest: case kMsgData: case kMsgCancel: case kMsgLookup:
    case kMsgLookupResult: case kMsgSegData:
      if (e.requestId == 0) { *why = "requestId 0 on a request-scoped message"; return kMalformed; }
      break;
    default: break;
  }
  return kOk;
}

// ---- 3.4 HELLO ------------------------------------------------------------------------

struct Hello {
  uint32_t protoMax = kProtoVersion, protoMin = kProtoMin, build = 0, caps = 0;
  std::string clientName, token;
  TlvList ext;
};

inline Outcome ParseHello(const uint8_t *p, size_t n, Hello *h, std::string *why) {
  Reader r(p, n);
  Verdict v;
  h->protoMax = r.u32();
  h->protoMin = r.u32();
  h->build = r.u32();
  h->caps = r.u32();
  h->clientName = ReadText(r, v, "clientName is not text");
  h->token = ReadText(r, v, "token is not text");
  h->ext = ReadTlv(r, v, nullptr, 0);
  if (!r.ok()) v.Malformed("HELLO truncated");
  else if (r.left()) v.Malformed("bytes after HELLO");
  if (h->protoMin < kProtoMin || h->protoMin > h->protoMax)
    v.Malformed("protoMin must be >= 4 and <= protoMax");
  if (h->token.size() > kTokenMax) v.Malformed("token longer than 128 bytes");
  *why = v.why();
  return v.outcome();
}
inline void EncodeHello(std::vector<uint8_t> *pay, const Hello &h) {
  Writer w(pay);
  w.u32(h.protoMax); w.u32(h.protoMin); w.u32(h.build); w.u32(h.caps);
  w.str8(h.clientName); w.str8(h.token); WriteTlv(w, h.ext);
}

// ---- 3.4 WELCOME ---------------------------------------------------------------------

struct Welcome {
  uint32_t protoSession = kProtoVersion, caps = 0;
  uint32_t maxObjs = 64, maxRows = 20000, maxChunkRows = 500;
  uint32_t maxPayload = 4u * 1024u * 1024u, maxCells = 100000;
  uint8_t maxProfiles = 16;
  std::string serverName, engine, datasetId;
  TlvList caps_;   // capability TLVs (A.3), raw; see Capabilities below
};

inline const uint16_t kWelcomeTags[] = {
  kCapTagKinds, kCapTagObservers, kCapTagPlanesFormsFrames, kCapTagCorrections,
  kCapTagOrbit, kCapTagColumns, kCapTagZodiacs, kCapTagSiderealPlanes,
  kCapTagTimeScales, kCapTagCoverage, kCapTagCatalogs, kCapTagDeltaT,
  kCapTagPrecession, kCapTagRate, kCapTagSegments, kCapTagLookup,
  kCapTagHypotheticals, kCapTagEquinoxes,
};

inline Outcome ParseWelcome(const uint8_t *p, size_t n, Welcome *w, std::string *why) {
  Reader r(p, n);
  Verdict v;
  w->protoSession = r.u32();
  w->caps = r.u32();
  w->maxObjs = r.u32();
  w->maxRows = r.u32();
  w->maxChunkRows = r.u32();
  w->maxPayload = r.u32();
  w->maxCells = r.u32();
  w->maxProfiles = r.u8();
  uint8_t res8 = r.u8();
  uint16_t res16 = r.u16();
  w->serverName = ReadText(r, v, "serverName is not text");
  w->engine = ReadText(r, v, "engine is not text");
  w->datasetId = ReadText(r, v, "datasetId is not text");
  w->caps_ = ReadTlv(r, v, kWelcomeTags, sizeof(kWelcomeTags) / sizeof(kWelcomeTags[0]));
  if (!r.ok()) v.Malformed("WELCOME truncated");
  else if (r.left()) v.Malformed("bytes after WELCOME");
  if (res8 || res16) v.Malformed("WELCOME reserved fields nonzero");
  if (w->protoSession < kProtoMin) v.Malformed("WELCOME session below 4");
  if (!w->maxObjs || !w->maxRows || !w->maxChunkRows || !w->maxCells || !w->maxProfiles)
    v.Malformed("a WELCOME limit is zero");
  *why = v.why();
  return v.outcome();
}
inline void EncodeWelcome(std::vector<uint8_t> *pay, const Welcome &w) {
  Writer o(pay);
  o.u32(w.protoSession); o.u32(w.caps); o.u32(w.maxObjs); o.u32(w.maxRows);
  o.u32(w.maxChunkRows); o.u32(w.maxPayload); o.u32(w.maxCells);
  o.u8(w.maxProfiles); o.u8(0); o.u16(0);
  o.str8(w.serverName); o.str8(w.engine); o.str8(w.datasetId);
  WriteTlv(o, w.caps_);
}

// ---- 3.4 REQUEST ----------------------------------------------------------------------

struct Profile {
  uint8_t observer = kObsGeo, plane = kPlaneEcliptic, form = kFormSpherical,
          frame = kFrameTrueOfDate, corrections = kCorrMask, speeds = 1,
          siderealPlane = kSidPlaneDate;
  int32_t observerBody = 0;
  double siteLonEastDeg = 0.0, siteLatDeg = 0.0, siteHeightM = 0.0;
  Time anchorEpoch;
  double anchorAyanamsaDeg = 0.0;
  uint32_t columns = 0;
  std::string zodiac;   // "" tropical
  TlvList ext;
};

struct Object {
  uint8_t kind = kObjBody;
  uint8_t profile = 0;
  int32_t naif = 0;                    // body, orbit point
  uint8_t point = 0, method = 0;       // orbit point
  std::string name;                    // star, hypothetical, elements, designation
  // elements
  Time epoch;
  uint8_t equinox = kEqJ2000, centre = 0, nTerms = 1;
  double equinoxJd = 0.0;
  std::vector<double> coef;            // 6 x nTerms: M, a, e, argp, node, incl
  // Host-only (never on the wire): the source's own id for the body, so a
  // local plugin can make exactly today's call (EPHEMERIS_PLUGINS_PLAN.md 4.1).
  int32_t nNative = 0;
};

struct Request {
  // Delivery block.
  uint8_t precision = kPrecF64, priority = 0, representation = 0;
  uint32_t chunkRows = 0;
  float segTargetErrArcsec = 0.0f;
  // Question block.
  uint8_t timeScale = kTimeTT, timeMode = kTimeGrid;
  Time start;              // grid
  int64_t stepNs = 0;      // grid
  uint32_t nTime = 1;
  std::vector<Time> instants;   // list
  double deltaTSec = CanonicalNaN();
  std::vector<Profile> profiles;
  std::vector<Object> objs;
  TlvList ext;
  // Filled by ParseRequest: where the question block starts in the payload
  // (the cache key is datasetId + payload[questionOffset..], 3.7).
  size_t questionOffset = 12;

  // 3.5 row instant.
  Time RowTime(uint32_t row) const {
    if (timeMode == kTimeList) return instants[row];
    Time t = start;
    t.jd2 += (double)((int64_t)row * stepNs) / (double)kNsPerDay;
    return t;
  }
};

inline const uint16_t kRequestTags[] = { kReqTagPrecession, kReqTagEphemerisPin, kReqTagCatalogPin };

inline void ReadProfile(Reader &r, Verdict &v, Profile *pf) {
  pf->observer = r.u8();
  pf->plane = r.u8();
  pf->form = r.u8();
  pf->frame = r.u8();
  pf->corrections = r.u8();
  pf->speeds = r.u8();
  pf->siderealPlane = r.u8();
  uint8_t reserved = r.u8();
  pf->observerBody = r.i32();
  pf->siteLonEastDeg = r.f64();
  pf->siteLatDeg = r.f64();
  pf->siteHeightM = r.f64();
  pf->anchorEpoch.jd1 = r.f64();
  pf->anchorEpoch.jd2 = r.f64();
  pf->anchorAyanamsaDeg = r.f64();
  pf->columns = r.u32();
  pf->zodiac = ReadText(r, v, "zodiac is not text");
  pf->ext = ReadTlv(r, v, nullptr, 0);
  if (!r.ok()) return;
  if (reserved) v.Malformed("profile reserved byte nonzero");
  if (pf->speeds > 1) v.Malformed("speeds must be 0 or 1");
  if (pf->observer > kObserverMax) v.Unsupported("observer not in the registry");
  if (pf->plane > kPlaneEquator || pf->form > kFormRectangular || pf->frame > kFrameMax)
    v.Unsupported("plane, form or frame not in the registry");
  if (pf->corrections & ~kCorrMask) v.Unsupported("correction bits not in the registry");
  if (pf->siderealPlane > kSidPlaneMax) v.Unsupported("sidereal plane not in the registry");
  if (pf->columns & ~kColMask) v.Unsupported("column bits not in the registry");
  // Every float finite (3.1).
  if (!std::isfinite(pf->siteLonEastDeg) || !std::isfinite(pf->siteLatDeg) ||
      !std::isfinite(pf->siteHeightM) || !std::isfinite(pf->anchorEpoch.jd1) ||
      !std::isfinite(pf->anchorEpoch.jd2) || !std::isfinite(pf->anchorAyanamsaDeg)) {
    v.Malformed("profile float not finite");
    return;
  }
  // 3.5 unused fields are zero.
  if (pf->observer != kObsBody && pf->observerBody != 0)
    v.Malformed("observerBody set without a body observer");
  if (pf->observer == kObsTopo) {
    if (std::fabs(pf->siteLonEastDeg) > 180.0 || std::fabs(pf->siteLatDeg) > 90.0)
      v.Malformed("site longitude or latitude out of range");
  } else if (pf->siteLonEastDeg != 0.0 || pf->siteLatDeg != 0.0 || pf->siteHeightM != 0.0) {
    v.Malformed("site set without a topocentric observer");
  }
  if (std::fabs(pf->anchorEpoch.jd1) + std::fabs(pf->anchorEpoch.jd2) > kJdAbsMax)
    v.Malformed("anchor epoch outside |jd| <= 1e8");
  if (pf->zodiac.empty()) {
    if (pf->siderealPlane != kSidPlaneDate) v.Malformed("tropical profile with a sidereal plane");
    if (!pf->anchorEpoch.IsZero() || pf->anchorAyanamsaDeg != 0.0)
      v.Malformed("tropical profile with an anchor");
  } else if (ZodiacIsUser(pf->zodiac)) {
    if (pf->anchorEpoch.IsZero()) v.Malformed("user zodiac without an anchor epoch");
  } else {
    if (!pf->anchorEpoch.IsZero() || pf->anchorAyanamsaDeg != 0.0)
      v.Malformed("named zodiac with an anchor");
    if (ZodiacIndex(pf->zodiac) < 0) v.Unsupported("zodiac token not in the registry");
  }
}

inline void WriteProfile(Writer &w, const Profile &pf) {
  w.u8(pf.observer); w.u8(pf.plane); w.u8(pf.form); w.u8(pf.frame);
  w.u8(pf.corrections); w.u8(pf.speeds); w.u8(pf.siderealPlane); w.u8(0);
  w.i32(pf.observerBody);
  w.f64(pf.siteLonEastDeg); w.f64(pf.siteLatDeg); w.f64(pf.siteHeightM);
  WriteTime(w, pf.anchorEpoch);
  w.f64(pf.anchorAyanamsaDeg);
  w.u32(pf.columns);
  w.str8(pf.zodiac);
  WriteTlv(w, pf.ext);
}

// Returns false when the kind is unknown: its payload length is unknowable,
// so the parse cannot continue (the caller's verdict is already Unsupported).
inline bool ReadObject(Reader &r, Verdict &v, Object *o) {
  o->kind = r.u8();
  o->profile = r.u8();
  uint16_t reserved = r.u16();
  if (reserved) v.Malformed("object reserved field nonzero");
  switch (o->kind) {
    case kObjBody:
      o->naif = r.i32();
      break;
    case kObjOrbitPoint: {
      o->naif = r.i32();
      o->point = r.u8();
      o->method = r.u8();
      if (r.u16()) v.Malformed("orbit point reserved field nonzero");
      if (o->point > kOrbitPointMax) v.Unsupported("orbit point not in the registry");
      if (o->method > kOrbitMethodMax) v.Unsupported("orbit method not in the registry");
      break;
    }
    case kObjStar: case kObjHypothetical: case kObjDesignation:
      o->name = ReadText(r, v, "object name is not text");
      if (r.ok() && o->name.empty()) v.Malformed("empty object name");
      if (o->kind == kObjHypothetical && r.ok() && !o->name.empty()) {
        bool fKnown = false;
        for (int i = 0; i < kHypotheticalTokenCount; i++)
          if (o->name == kHypotheticalTokens[i]) fKnown = true;
        // A.15: "A server MAY serve more" -- an unknown token is a
        // per-object error at the server, not a codec refusal.
        (void)fKnown;
      }
      break;
    case kObjElements: {
      o->epoch = ReadTime(r, v);
      o->equinox = r.u8();
      o->centre = r.u8();
      o->nTerms = r.u8();
      if (r.u8()) v.Malformed("elements reserved byte nonzero");
      o->equinoxJd = r.f64();
      if (o->nTerms < 1 || o->nTerms > 5) {
        v.Malformed("elements nTerms must be 1..5");
        return false;   // the coefficient count is unknowable
      }
      o->coef.resize((size_t)6 * o->nTerms);
      for (double &c : o->coef) {
        c = r.f64();
        if (r.ok() && !std::isfinite(c)) v.Malformed("element coefficient not finite");
      }
      o->name = ReadText(r, v, "elements name is not text");
      if (o->equinox > kEquinoxMax) v.Unsupported("equinox not in the registry");
      if (o->centre > kCentreMax) v.Unsupported("elements centre not in the registry");
      if (!std::isfinite(o->equinoxJd)) v.Malformed("equinoxJd not finite");
      else if (o->equinox == kEqExplicit) {
        if (o->equinoxJd == 0.0 || std::fabs(o->equinoxJd) > kJdAbsMax)
          v.Malformed("explicit equinox without a valid JD");
      } else if (o->equinoxJd != 0.0) {
        v.Malformed("equinoxJd set without an explicit equinox");
      }
      break;
    }
    default:
      v.Unsupported("object kind not in the registry");
      return false;
  }
  return true;
}

inline void WriteObject(Writer &w, const Object &o) {
  w.u8(o.kind); w.u8(o.profile); w.u16(0);
  switch (o.kind) {
    case kObjBody: w.i32(o.naif); break;
    case kObjOrbitPoint: w.i32(o.naif); w.u8(o.point); w.u8(o.method); w.u16(0); break;
    case kObjStar: case kObjHypothetical: case kObjDesignation: w.str8(o.name); break;
    case kObjElements:
      WriteTime(w, o.epoch);
      w.u8(o.equinox); w.u8(o.centre); w.u8(o.nTerms); w.u8(0);
      w.f64(o.equinoxJd);
      for (double c : o.coef) w.f64(c);
      w.str8(o.name);
      break;
    default: break;
  }
}

inline Outcome ParseRequest(const uint8_t *p, size_t n, Request *q, std::string *why,
                            bool *pfIgnoredExt = nullptr) {
  Reader r(p, n);
  Verdict v;
  // Delivery block (12 bytes).
  q->precision = r.u8();
  q->priority = r.u8();
  q->representation = r.u8();
  uint8_t dres = r.u8();
  q->chunkRows = r.u32();
  q->segTargetErrArcsec = r.f32();
  q->questionOffset = 12;
  if (dres) v.Malformed("delivery reserved byte nonzero");
  if (q->precision > kPrecF32) v.Unsupported("precision not in the registry");
  if (q->priority > 1) v.Unsupported("priority not in the registry");
  if (q->representation > 1) v.Unsupported("representation not in the registry");
  if (!std::isfinite(q->segTargetErrArcsec)) v.Malformed("segment target not finite");
  else if (q->representation == 0 && q->segTargetErrArcsec != 0.0f)
    v.Malformed("segment target set for a samples request");
  else if (q->representation == 1 && !(q->segTargetErrArcsec > 0.0f))
    v.Malformed("segments request without a positive target error");

  // Question block: time.
  q->timeScale = r.u8();
  q->timeMode = r.u8();
  if (r.u16()) v.Malformed("time reserved field nonzero");
  if (q->timeScale > kTimeScaleMax) v.Unsupported("time scale not in the registry");
  q->instants.clear();
  if (q->timeMode == kTimeGrid) {
    q->start = ReadTime(r, v);
    q->stepNs = r.i64();
    q->nTime = r.u32();
    if (r.ok()) {
      if (q->nTime == 0) v.Malformed("nTime 0");
      else if (q->nTime == 1 && q->stepNs != 0) v.Malformed("stepNs nonzero with one row");
      else if (q->nTime > 1 && q->stepNs == 0) v.Malformed("stepNs 0 with several rows");
      if (q->nTime > 1 && q->stepNs != 0) {
        // (nTime-1) x |stepNs| must fit in i64 (3.5).
        uint64_t mag = q->stepNs < 0 ? (uint64_t)(-(q->stepNs + 1)) + 1u : (uint64_t)q->stepNs;
        if (mag > (uint64_t)INT64_MAX / (uint64_t)(q->nTime - 1))
          v.Malformed("grid span overflows i64 nanoseconds");
      }
    }
  } else if (q->timeMode == kTimeList) {
    q->nTime = r.u32();
    if (r.ok() && q->nTime == 0) v.Malformed("nTime 0");
    // Bounded by the bytes present before anything is allocated (3.8).
    if (r.ok() && (uint64_t)q->nTime * 16u > r.left()) {
      v.Malformed("instant list runs past the payload");
      *why = v.why();
      return v.outcome();
    }
    q->instants.reserve(q->nTime);
    for (uint32_t i = 0; i < q->nTime && r.ok(); i++) q->instants.push_back(ReadTime(r, v));
  } else {
    v.Unsupported("time mode not in the registry");
    *why = v.why();
    return v.outcome();
  }
  q->deltaTSec = r.f64();
  if (r.ok() && !std::isfinite(q->deltaTSec) && !IsCanonicalNaN(q->deltaTSec))
    v.Malformed("deltaTSec is neither finite nor the canonical NaN");

  // Profiles.
  uint8_t nProf = r.u8();
  if (r.ok() && nProf == 0) v.Malformed("no profiles");
  q->profiles.assign(nProf, Profile());
  for (Profile &pf : q->profiles) {
    if (!r.ok()) break;
    ReadProfile(r, v, &pf);
  }

  // Objects.
  uint16_t nObj = r.u16();
  if (r.ok() && nObj == 0) v.Malformed("no objects");
  if (r.ok() && (size_t)nObj * 8u > r.left()) {
    v.Malformed("object list runs past the payload");
    *why = v.why();
    return v.outcome();
  }
  q->objs.clear();
  q->objs.reserve(nObj);
  for (uint16_t i = 0; i < nObj && r.ok(); i++) {
    Object o;
    if (!ReadObject(r, v, &o)) {
      *why = v.why();
      return v.outcome();
    }
    if (o.profile >= nProf) v.Malformed("object names a profile that does not exist");
    q->objs.push_back(std::move(o));
  }
  q->ext = ReadTlv(r, v, kRequestTags, sizeof(kRequestTags) / sizeof(kRequestTags[0]),
                   pfIgnoredExt);
  for (const Tlv &e : q->ext) {
    std::string s;
    bool fKnown = e.tag == kReqTagPrecession || e.tag == kReqTagEphemerisPin ||
                  e.tag == kReqTagCatalogPin;
    if (fKnown && !TlvStr8(e, &s)) v.Malformed("REQUEST extension payload is not one str8");
  }
  if (!r.ok()) v.Malformed("REQUEST truncated");
  else if (r.left()) v.Malformed("bytes after REQUEST");

  // Segments constraints (3.4 SEGDATA rules).
  if (!v.malformed() && q->representation == 1) {
    if (q->timeMode != kTimeGrid) v.Unsupported("segments need a grid");
    for (const Profile &pf : q->profiles)
      if (pf.form != kFormRectangular || pf.columns != 0)
        v.Unsupported("segments need rectangular profiles without extra columns");
  }
  *why = v.why();
  return v.outcome();
}

inline void EncodeRequest(std::vector<uint8_t> *pay, const Request &q) {
  Writer w(pay);
  w.u8(q.precision); w.u8(q.priority); w.u8(q.representation); w.u8(0);
  w.u32(q.chunkRows); w.f32(q.segTargetErrArcsec);
  w.u8(q.timeScale); w.u8(q.timeMode); w.u16(0);
  if (q.timeMode == kTimeGrid) {
    WriteTime(w, q.start); w.i64(q.stepNs); w.u32(q.nTime);
  } else {
    w.u32((uint32_t)q.instants.size());
    for (const Time &t : q.instants) WriteTime(w, t);
  }
  w.f64(q.deltaTSec);
  w.u8((uint8_t)q.profiles.size());
  for (const Profile &pf : q.profiles) WriteProfile(w, pf);
  w.u16((uint16_t)q.objs.size());
  for (const Object &o : q.objs) WriteObject(w, o);
  WriteTlv(w, q.ext);
}

// ---- 3.4 META, source table, DATA ----------------------------------------------------

struct Meta {
  int32_t rowsOk = 0;
  uint16_t errCode = kOErrNone;
  uint8_t sourceIdx = kSourceNone, flags = 0;
  int32_t resolvedNaif = kNaifNone;
  uint32_t firstFailedRow = kRowNone;
  std::string name, errText;
};

inline void ReadSources(Reader &r, Verdict &v, std::vector<std::string> *src) {
  uint8_t n = r.u8();
  src->clear();
  for (uint8_t i = 0; i < n && r.ok(); i++) src->push_back(ReadText(r, v, "source name is not text"));
}
inline void WriteSources(Writer &w, const std::vector<std::string> &src) {
  w.u8((uint8_t)src.size());
  for (const std::string &s : src) w.str8(s);
}
inline void ReadMeta(Reader &r, Verdict &v, Meta *m, size_t nSources) {
  m->rowsOk = r.i32();
  m->errCode = r.u16();
  m->sourceIdx = r.u8();
  m->flags = r.u8();
  m->resolvedNaif = r.i32();
  m->firstFailedRow = r.u32();
  m->name = ReadText(r, v, "object name is not text");
  m->errText = ReadText(r, v, "error text is not text");
  if (!r.ok()) return;
  if (m->rowsOk < 0) v.Malformed("META rowsOk negative");
  if (m->sourceIdx != kSourceNone && m->sourceIdx >= nSources)
    v.Malformed("META names a source that is not in the table");
  if (m->flags & ~(uint8_t)0x1F) v.Malformed("META flag bits not in the registry");
}
inline void WriteMeta(Writer &w, const Meta &m) {
  w.i32(m.rowsOk); w.u16(m.errCode); w.u8(m.sourceIdx); w.u8(m.flags);
  w.i32(m.resolvedNaif); w.u32(m.firstFailedRow); w.str8(m.name); w.str8(m.errText);
}

inline int PopCount(uint32_t x) { int c = 0; while (x) { c += (int)(x & 1u); x >>= 1; } return c; }

struct DataChunk {
  uint32_t chunkIndex = 0, iTime = 0, nRows = 0, totalRows = 0;
  uint8_t precision = kPrecF64, flags = 0;
  uint16_t nObj = 0;
  uint32_t columnsPresent = 0;
  std::vector<std::string> sources;   // when flags & kChunkMeta
  std::vector<Meta> meta;
  std::vector<double> values;         // object-major, nObj x nRows x nCols
  int Cols() const { return 6 + PopCount(columnsPresent); }
};

inline Outcome ParseData(const uint8_t *p, size_t n, DataChunk *d, std::string *why) {
  Reader r(p, n);
  Verdict v;
  d->chunkIndex = r.u32();
  d->iTime = r.u32();
  d->nRows = r.u32();
  d->totalRows = r.u32();
  d->precision = r.u8();
  d->flags = r.u8();
  d->nObj = r.u16();
  d->columnsPresent = r.u32();
  if (!r.ok()) { *why = "DATA truncated"; return kMalformed; }
  if (d->flags & ~(uint8_t)7) v.Malformed("DATA chunk flag bits not in the registry");
  if (d->precision > kPrecF32) v.Unsupported("precision not in the registry");
  if (d->columnsPresent & ~kColMask) v.Unsupported("column bits not in the registry");
  if (d->nRows == 0 || d->nObj == 0) v.Malformed("empty DATA chunk");
  if ((uint64_t)d->iTime + d->nRows > d->totalRows) v.Malformed("DATA rows run past totalRows");
  if (d->chunkIndex == 0 && !(d->flags & kChunkMeta)) v.Malformed("chunk 0 without metadata");
  d->sources.clear();
  d->meta.clear();
  if (d->flags & kChunkMeta) {
    ReadSources(r, v, &d->sources);
    d->meta.assign(d->nObj, Meta());
    for (Meta &m : d->meta) {
      if (!r.ok()) break;
      ReadMeta(r, v, &m, d->sources.size());
    }
  }
  if (v.outcome() != kOk || !r.ok()) {
    *why = r.ok() ? v.why() : "DATA truncated";
    return r.ok() ? v.outcome() : kMalformed;
  }
  uint64_t cells = (uint64_t)d->nObj * d->nRows * (uint64_t)d->Cols();
  size_t esz = d->precision == kPrecF32 ? 4 : 8;
  if (cells * esz != r.left()) { *why = "DATA values do not fill the payload exactly"; return kMalformed; }
  d->values.resize((size_t)cells);
  for (double &x : d->values) x = d->precision == kPrecF32 ? (double)r.f32() : r.f64();
  *why = v.why();
  return v.outcome();
}
inline void EncodeData(std::vector<uint8_t> *pay, const DataChunk &d) {
  Writer w(pay);
  w.u32(d.chunkIndex); w.u32(d.iTime); w.u32(d.nRows); w.u32(d.totalRows);
  w.u8(d.precision); w.u8(d.flags); w.u16(d.nObj); w.u32(d.columnsPresent);
  if (d.flags & kChunkMeta) {
    WriteSources(w, d.sources);
    for (const Meta &m : d.meta) WriteMeta(w, m);
  }
  for (double x : d.values) {
    if (d.precision == kPrecF32) w.f32((float)x);
    else w.f64(x);
  }
}

// ---- 3.4 ERROR, CANCEL, PING, PONG ----------------------------------------------------

struct Error {
  uint16_t code = kErrInternal, flags = 0;
  uint32_t retryAfterMs = 0;
  std::string text;
  TlvList ext;
};

inline Outcome ParseError(const uint8_t *p, size_t n, Error *e, std::string *why) {
  Reader r(p, n);
  Verdict v;
  e->code = r.u16();
  e->flags = r.u16();
  e->retryAfterMs = r.u32();
  e->text = ReadText(r, v, "error text is not text");
  e->ext = ReadTlv(r, v, nullptr, 0);
  if (!r.ok()) v.Malformed("ERROR truncated");
  else if (r.left()) v.Malformed("bytes after ERROR");
  if (e->flags & ~(uint16_t)(kErrFlagClosing | kErrFlagRetryable))
    v.Malformed("ERROR flag bits not in the registry");
  if (e->code == 0) v.Malformed("ERROR code 0");
  *why = v.why();
  return v.outcome();
}
inline void EncodeError(std::vector<uint8_t> *pay, const Error &e) {
  Writer w(pay);
  w.u16(e.code); w.u16(e.flags); w.u32(e.retryAfterMs); w.str8(e.text); WriteTlv(w, e.ext);
}

// 3.3 step 5: the refusal an older (version 2-3) client can read, in its own
// layout: u32 requestId, i32 code, NUL-terminated text.
struct LegacyError {
  uint32_t requestId = 0;
  int32_t code = 0;
  std::string text;
};
inline Outcome ParseLegacyError(const uint8_t *p, size_t n, LegacyError *e, std::string *why) {
  Reader r(p, n);
  e->requestId = r.u32();
  e->code = r.i32();
  size_t left = r.left();
  const uint8_t *s = r.bytes(left);
  if (!r.ok() || left == 0 || s[left - 1] != 0 || memchr(s, 0, left) != s + left - 1) {
    *why = "legacy ERROR text is not one NUL-terminated string";
    return kMalformed;
  }
  e->text.assign((const char *)s, left - 1);
  return kOk;
}
inline void EncodeLegacyError(std::vector<uint8_t> *pay, const LegacyError &e) {
  Writer w(pay);
  w.u32(e.requestId); w.i32(e.code); w.raw(e.text.data(), e.text.size()); w.u8(0);
}

// ---- 3.4 LOOKUP and LOOKUP_RESULT -----------------------------------------------------

struct Lookup {
  uint16_t maxMatches = 8;
  uint8_t flags = 0;   // bit 0 prefix, bit 1 hypotheticals, bit 2 stars
  std::string query;
  TlvList ext;
};
inline Outcome ParseLookup(const uint8_t *p, size_t n, Lookup *l, std::string *why) {
  Reader r(p, n);
  Verdict v;
  l->maxMatches = r.u16();
  l->flags = r.u8();
  if (r.u8()) v.Malformed("LOOKUP reserved byte nonzero");
  l->query = ReadText(r, v, "query is not text");
  l->ext = ReadTlv(r, v, nullptr, 0);
  if (!r.ok()) v.Malformed("LOOKUP truncated");
  else if (r.left()) v.Malformed("bytes after LOOKUP");
  if (l->maxMatches == 0) v.Malformed("LOOKUP maxMatches 0");
  if (l->flags & ~(uint8_t)7) v.Malformed("LOOKUP flag bits not in the registry");
  if (r.ok() && l->query.empty()) v.Malformed("empty LOOKUP query");
  *why = v.why();
  return v.outcome();
}
inline void EncodeLookup(std::vector<uint8_t> *pay, const Lookup &l) {
  Writer w(pay);
  w.u16(l.maxMatches); w.u8(l.flags); w.u8(0); w.str8(l.query); WriteTlv(w, l.ext);
}

struct Match {
  uint8_t quality = 0, sourceIdx = 0;
  Object obj;
  std::string canonicalName, designation;
  Time validMin, validMax;
};
struct LookupResult {
  uint8_t flags = 0;   // bit 0 truncated
  std::vector<std::string> sources;
  std::vector<Match> matches;
};
inline Outcome ParseLookupResult(const uint8_t *p, size_t n, LookupResult *lr, std::string *why) {
  Reader r(p, n);
  Verdict v;
  uint16_t count = r.u16();
  lr->flags = r.u8();
  if (lr->flags & ~(uint8_t)1) v.Malformed("LOOKUP_RESULT flag bits not in the registry");
  ReadSources(r, v, &lr->sources);
  lr->matches.clear();
  for (uint16_t i = 0; i < count && r.ok(); i++) {
    Match m;
    m.quality = r.u8();
    m.sourceIdx = r.u8();
    if (r.u16()) v.Malformed("match reserved field nonzero");
    if (m.quality > 2) v.Unsupported("match quality not in the registry");
    if (m.sourceIdx >= lr->sources.size()) v.Malformed("match names a source not in the table");
    if (!ReadObject(r, v, &m.obj)) { *why = v.why(); return v.outcome(); }
    if (m.obj.profile != 0) v.Malformed("match object profile must be 0");
    m.canonicalName = ReadText(r, v, "canonical name is not text");
    m.designation = ReadText(r, v, "designation is not text");
    m.validMin = ReadTime(r, v);
    m.validMax = ReadTime(r, v);
    lr->matches.push_back(std::move(m));
  }
  if (!r.ok()) v.Malformed("LOOKUP_RESULT truncated");
  else if (r.left()) v.Malformed("bytes after LOOKUP_RESULT");
  *why = v.why();
  return v.outcome();
}
inline void EncodeLookupResult(std::vector<uint8_t> *pay, const LookupResult &lr) {
  Writer w(pay);
  w.u16((uint16_t)lr.matches.size());
  w.u8(lr.flags);
  WriteSources(w, lr.sources);
  for (const Match &m : lr.matches) {
    w.u8(m.quality); w.u8(m.sourceIdx); w.u16(0);
    WriteObject(w, m.obj);
    w.str8(m.canonicalName); w.str8(m.designation);
    WriteTime(w, m.validMin); WriteTime(w, m.validMax);
  }
}

// ---- 3.4 SEGDATA -------------------------------------------------------------------------

struct Segment {
  Time mid;
  double halfSpanDays = 0.0;
  uint8_t degree = 0;
  float errArcsec = 0.0f, errRelDist = 0.0f;
  std::vector<double> coef;   // 3 x (degree + 1): x0..xd, y0..yd, z0..zd

  // 3.4 evaluation: position (AU) and velocity (AU/day) at t.
  void Eval(const Time &t, double pos[3], double vel[3]) const {
    double tau = ((t.jd1 - mid.jd1) + (t.jd2 - mid.jd2)) / halfSpanDays;
    int nc = degree + 1;
    for (int axis = 0; axis < 3; axis++) {
      const double *c = coef.data() + axis * nc;
      // Clenshaw for the value; the derivative through T'k = k U(k-1).
      double t0 = 1.0, t1 = tau, u0 = 1.0, u1 = 2.0 * tau;
      double x = c[0], dx = 0.0;
      if (nc > 1) { x += c[1] * t1; dx += c[1] * 1.0 * u0; }
      for (int k = 2; k < nc; k++) {
        double t2 = 2.0 * tau * t1 - t0;
        double u2 = 2.0 * tau * u1 - u0;
        x += c[k] * t2;
        dx += c[k] * k * u1;
        t0 = t1; t1 = t2; u0 = u1; u1 = u2;
      }
      pos[axis] = x;
      vel[axis] = dx / halfSpanDays;
    }
  }
};

struct SegDataChunk {
  uint32_t chunkIndex = 0;
  uint8_t flags = 0;
  uint16_t nObj = 0, iObj = 0, nObjChunk = 0;
  std::vector<std::string> sources;
  std::vector<Meta> meta;
  std::vector<std::vector<Segment>> segs;   // nObjChunk entries
};

inline Outcome ParseSegData(const uint8_t *p, size_t n, SegDataChunk *s, std::string *why) {
  Reader r(p, n);
  Verdict v;
  s->chunkIndex = r.u32();
  s->flags = r.u8();
  if (r.u8()) v.Malformed("SEGDATA reserved byte nonzero");
  s->nObj = r.u16();
  s->iObj = r.u16();
  s->nObjChunk = r.u16();
  if (r.u32()) v.Malformed("SEGDATA reserved field nonzero");
  if (!r.ok()) { *why = "SEGDATA truncated"; return kMalformed; }
  if (s->flags & ~(uint8_t)7) v.Malformed("SEGDATA chunk flag bits not in the registry");
  if (s->nObj == 0 || (uint32_t)s->iObj + s->nObjChunk > s->nObj)
    v.Malformed("SEGDATA object range outside nObj");
  if (s->chunkIndex == 0 && !(s->flags & kChunkMeta)) v.Malformed("chunk 0 without metadata");
  s->sources.clear();
  s->meta.clear();
  if (s->flags & kChunkMeta) {
    ReadSources(r, v, &s->sources);
    s->meta.assign(s->nObj, Meta());
    for (Meta &m : s->meta) {
      if (!r.ok()) break;
      ReadMeta(r, v, &m, s->sources.size());
    }
  }
  s->segs.assign(s->nObjChunk, std::vector<Segment>());
  for (auto &list : s->segs) {
    uint32_t nSeg = r.u32();
    if (!r.ok()) break;
    if ((uint64_t)nSeg * 44u > r.left()) { v.Malformed("segment list runs past the payload"); break; }
    list.resize(nSeg);
    for (Segment &g : list) {
      g.mid = ReadTime(r, v);
      g.halfSpanDays = r.f64();
      g.degree = r.u8();
      const uint8_t *res = r.bytes(3);
      if (res && (res[0] | res[1] | res[2])) v.Malformed("segment reserved bytes nonzero");
      g.errArcsec = r.f32();
      g.errRelDist = r.f32();
      if (!r.ok()) break;
      if (!(g.halfSpanDays > 0.0) || !std::isfinite(g.halfSpanDays))
        v.Malformed("segment half span not positive and finite");
      if (!std::isfinite(g.errArcsec) || !std::isfinite(g.errRelDist) || g.errArcsec < 0.0f ||
          g.errRelDist < 0.0f)
        v.Malformed("segment error bound not a finite non-negative number");
      if (g.degree > kSegDegreeMax) { v.Malformed("segment degree past 31"); break; }
      g.coef.resize((size_t)3 * (g.degree + 1u));
      for (double &c : g.coef) {
        c = r.f64();
        if (r.ok() && !std::isfinite(c)) v.Malformed("segment coefficient not finite");
      }
    }
  }
  if (!r.ok()) v.Malformed("SEGDATA truncated");
  else if (r.left()) v.Malformed("bytes after SEGDATA");
  *why = v.why();
  return v.outcome();
}
inline void EncodeSegData(std::vector<uint8_t> *pay, const SegDataChunk &s) {
  Writer w(pay);
  w.u32(s.chunkIndex); w.u8(s.flags); w.u8(0); w.u16(s.nObj); w.u16(s.iObj);
  w.u16(s.nObjChunk); w.u32(0);
  if (s.flags & kChunkMeta) {
    WriteSources(w, s.sources);
    for (const Meta &m : s.meta) WriteMeta(w, m);
  }
  for (const auto &list : s.segs) {
    w.u32((uint32_t)list.size());
    for (const Segment &g : list) {
      WriteTime(w, g.mid); w.f64(g.halfSpanDays); w.u8(g.degree);
      w.u8(0); w.u8(0); w.u8(0);
      w.f32(g.errArcsec); w.f32(g.errRelDist);
      for (double c : g.coef) w.f64(c);
    }
  }
}

// ---- whole messages ------------------------------------------------------------------------

// Parses one complete frame (envelope + payload) as the receiver would,
// before any session state: the outcome is the spec's for a peer that sent
// exactly these bytes. Used by the conformance test and by fuzzing.
inline Outcome ParseFrame(const uint8_t *p, size_t n, Envelope *env, std::string *why) {
  Outcome o = ParseEnvelope(p, n, env, why);
  if (o != kOk) return o;
  const uint8_t *pay = p + kEnvelopeSize;
  size_t len = env->payloadLen;
  if (env->version < kProtoMin) {
    // Only a server's legacy refusal is ever written below version 4.
    if (env->type != kMsgError) { *why = "message below version 4"; return kUnsupported; }
    LegacyError le;
    return ParseLegacyError(pay, len, &le, why);
  }
  if ((o = CheckRequestId(*env, why)) != kOk) return o;
  // HELLO's layout is frozen for every version >= 4 (3.3); anything else is
  // read as version 4 here, the session check being the caller's.
  switch (env->type) {
    case kMsgHello: { Hello h; return ParseHello(pay, len, &h, why); }
    case kMsgWelcome: { Welcome w; return ParseWelcome(pay, len, &w, why); }
    case kMsgRequest: { Request q; return ParseRequest(pay, len, &q, why); }
    case kMsgData: { DataChunk d; return ParseData(pay, len, &d, why); }
    case kMsgError: { Error e; return ParseError(pay, len, &e, why); }
    case kMsgPing: case kMsgPong: case kMsgCancel:
      if (len != 0) { *why = "PING, PONG and CANCEL carry no payload"; return kMalformed; }
      return kOk;
    case kMsgLookup: { Lookup l; return ParseLookup(pay, len, &l, why); }
    case kMsgLookupResult: { LookupResult lr; return ParseLookupResult(pay, len, &lr, why); }
    case kMsgSegData: { SegDataChunk s; return ParseSegData(pay, len, &s, why); }
    default:
      *why = "unknown message type";
      return kUnsupported;   // ERROR 3 at the session; not a malformed frame
  }
}

// Re-encodes a frame that parsed kOk; the result must equal the input
// (3.9). Returns false for a type this does not re-encode.
inline bool ReencodeFrame(const uint8_t *p, size_t n, std::vector<uint8_t> *out) {
  Envelope env;
  std::string why;
  if (ParseFrame(p, n, &env, &why) != kOk) return false;
  const uint8_t *pay = p + kEnvelopeSize;
  size_t len = env.payloadLen;
  std::vector<uint8_t> body;
  if (env.version < kProtoMin) {
    LegacyError le;
    ParseLegacyError(pay, len, &le, &why);
    EncodeLegacyError(&body, le);
  } else {
    switch (env.type) {
      case kMsgHello: { Hello h; ParseHello(pay, len, &h, &why); EncodeHello(&body, h); break; }
      case kMsgWelcome: { Welcome w; ParseWelcome(pay, len, &w, &why); EncodeWelcome(&body, w); break; }
      case kMsgRequest: { Request q; ParseRequest(pay, len, &q, &why); EncodeRequest(&body, q); break; }
      case kMsgData: { DataChunk d; ParseData(pay, len, &d, &why); EncodeData(&body, d); break; }
      case kMsgError: { Error e; ParseError(pay, len, &e, &why); EncodeError(&body, e); break; }
      case kMsgPing: case kMsgPong: case kMsgCancel: break;
      case kMsgLookup: { Lookup l; ParseLookup(pay, len, &l, &why); EncodeLookup(&body, l); break; }
      case kMsgLookupResult: {
        LookupResult lr; ParseLookupResult(pay, len, &lr, &why); EncodeLookupResult(&body, lr); break;
      }
      case kMsgSegData: { SegDataChunk s; ParseSegData(pay, len, &s, &why); EncodeSegData(&body, s); break; }
      default: return false;
    }
  }
  out->clear();
  WriteEnvelope(out, env.type, env.requestId, body.size(), env.version, env.flags);
  out->insert(out->end(), body.begin(), body.end());
  return true;
}

}  // namespace eph4

#endif  // EPHPROTO4_H
