#!/usr/bin/env python3
"""ephparam.h: the shared ephemeris-parameter index space, generated.

All parameters of all sources share one index space (EPHEMERIS_PLUGINS_PLAN.md
4.3): us.rgszEphParam[] is indexed by it, and the command-line key of a
parameter is its source's key, a dot, and its own key ("-bP server.url
wss://host"). The space must be stable while the table grows -- a settings
file written against one generation must load under every later one -- so the
enum is generated rather than typed, the same way settingsfields.h and
ephsrv/registries.json are, and `make check` regenerates and diffs it.

The table below is the one copy of the parameters. The plan's own 4.2 table
is cross-checked against it, so the two cannot drift: every source named
there with parameters must appear here with the same parameter keys, and a
source that gains or loses a parameter in the plan fails this generator
loudly until the table below changes with it.

    python3 tools/gen-eph-params.py            # write ephparam.h
    python3 tools/gen-eph-params.py --stdout   # print it (make check diffs)
"""

import os
import re
import sys

PLAN = "EPHEMERIS_PLUGINS_PLAN.md"
OUT = "ephparam.h"

# Every declared parameter, in index order. Appended to, never reordered and
# never reused (the same rule the protocol's registries keep): a name here is
# a settings file's index forever.
#
# key      -- the parameter's own key, after the source's in "source.key"
# label    -- dialogs (section 4.3's EPHPARAM.szLabel)
# kind     -- an epk* value; a dialog masks epkToken and offers Browse for
#             epkPath and epkFile
# default  -- "" means the source's own default
#
# Sources with no parameters (swiss uses the -Yi paths; moshier, horizons,
# matrix and none declare none) have no rows here.
PARAMS = [
    ("jpl", "file",        "JPL file",    "epkFile",  ""),
    # All three are FILE paths, resolved on the -Yi search paths by
    # FEphPromFindFile() and handed to prometheia_engine_open(),
    # _add_catalog() and _add_perturbers(). They were declared here as
    # free text while a second, divergent copy of the same three lived
    # inside ephprom.cpp saying epkFile -- and nothing read either one,
    # so a dialog's Browse button depended on which table it asked.
    ("prometheia", "ephemeris",  "Ephemeris File",     "epkFile", ""),
    ("prometheia", "catalog",    "Small-body Catalog", "epkFile", ""),
    ("prometheia", "perturbers", "Perturber Kernel",   "epkFile", ""),
    ("server", "url",   "Server Address", "epkUrl",   ""),
    ("server", "token", "Server Token",   "epkToken", ""),
]


def plan_params():
    """The parameters the plan's own 4.2 table names, source by source.

    The table's rows read `| key | module | kind | parameters | notes |`;
    the parameters cell is a comma-separated list of `quoted` keys or the
    word "none". A row whose shape this cannot read stops the generator
    rather than passing silently -- a table whose shape changed is a
    specification event, not a parsing detail.
    """
    text = open(PLAN, encoding="utf-8").read()
    m = re.search(r"^### 4\.2 Built-in sources$(.*?)^### 4\.3", text,
                  re.S | re.M)
    if not m:
        raise SystemExit("EPHEMERIS_PLUGINS_PLAN.md: no section 4.2 table")
    rows = {}
    for line in m.group(1).split("\n"):
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != 5 or cells[0] in ("key", "") or set(cells[0]) <= {"-"}:
            continue
        key, params = cells[0].strip("`"), cells[3]
        if params in ("(uses `-Yi` paths)", "—", "none"):
            rows[key] = []
            continue
        keys = re.findall(r"`([^`]*)`", params)
        if not keys:
            raise SystemExit("4.2 row %r: unreadable parameters cell %r"
                             % (key, params))
        rows[key] = keys
    if not rows:
        raise SystemExit("EPHEMERIS_PLUGINS_PLAN.md: 4.2 table parsed to "
                         "nothing")
    return rows


def main():
    fstdout = "--stdout" in sys.argv
    # Cross-check the table against the plan's own 4.2 table.
    want = plan_params()
    have = {}
    for src, key, label, kind, default in PARAMS:
        have.setdefault(src, []).append(key)
    for src in sorted(set(want) | set(have)):
        if want.get(src, []) != have.get(src, []):
            raise SystemExit(
                "PARAMS disagrees with the plan's 4.2 table for %r: plan says "
                "%r, the generator's table says %r" %
                (src, want.get(src, ["none"]), have.get(src, ["none"])))

    out = []
    out.append("/*")
    out.append("** GENERATED by tools/gen-eph-params.py from the parameter "
               "table it carries --")
    out.append("** do not edit; regenerate and diff with make check.")
    out.append("**")
    out.append("** The shared parameter index space (EPHEMERIS_PLUGINS_PLAN.md"
               " 4.3): one")
    out.append("** index per parameter of every built-in source, all sources "
               "in one")
    out.append("** space. us.rgszEphParam[] is indexed by these, and the "
               "command-line key")
    out.append("** of a parameter is its source's key, a dot, and its own key"
               " (\"-bP")
    out.append("** server.url wss://host\"). Names are appended and never "
               "reordered and never")
    out.append("** reused, so a settings file's meanings survive the table "
               "growing.")
    out.append("*/")
    out.append("")
    out.append("#ifndef _EPHPARAM_H")
    out.append("#define _EPHPARAM_H")
    out.append("")
    out.append("enum {")
    cchMax = max(len("ep" + src[0].upper() + src[1:] + key[0].upper() +
      key[1:]) for src, key, label, kind, default in PARAMS)
    for src, key, label, kind, default in PARAMS:
        szName = "ep" + src[0].upper() + src[1:] + key[0].upper() + key[1:]
        out.append("  %s,%s// %s: %s" % (szName,
          " " * (cchMax + 2 - len(szName)), src, key))
    out.append("  cEphParam")
    out.append("};")
    out.append("")
    out.append("// The rows, in the enum's order. The EPHPARAMROW type that"
               " carries them")
    out.append("// and the table's extern are ephem.h's, hand-written: they"
               " name EPHPARAM,")
    out.append("// which ephem.h itself defines, and this header is included"
               " by astrolog.h")
    out.append("// BEFORE that, because US sizes us.rgszEphParam[] with"
               " cEphParam. The macro")
    out.append("// only expands where it is used (ephem.cpp's one"
               " definition), so its")
    out.append("// epk* tokens need not exist here.")
    out.append("")
    out.append("#define EphParamRowsGenerated() \\")
    out.append("  { \\")
    for i, (src, key, label, kind, default) in enumerate(PARAMS):
        szRow = "    {\"%s\", {\"%s\", \"%s\", %s, \"%s\"}}" % \
          (src, key, label, kind, default)
        szRow += "," if i < len(PARAMS) - 1 else ""
        out.append(szRow + (" \\" if i < len(PARAMS) - 1 else " \\\n  }"))
    out.append("")

    out.append("#endif // _EPHPARAM_H")
    text = "\n".join(out) + "\n"
    if fstdout:
        sys.stdout.write(text)
    else:
        with open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
          "..", OUT), "w", encoding="utf-8", newline="\n") as file:
            file.write(text)


main()
