#!/usr/bin/env python3
"""Generate settingsfields.h: every scalar member of US and GS, by name.

The settings writer is a hand-maintained list and the settings reader is
the switch registry; nothing in the program knows which fields the pair is
supposed to carry. This table gives a test the vocabulary to ask about all
of them at once -- poison every field, replay a saved file, and name the
ones that did not come back -- instead of one assertion per switch that
somebody remembered to write.

Members are read straight out of astrolog.h, with the section comment they
sit under and the switch their trailing comment names, both of which the
struct has always carried:

    // Chart types
    flag fListing;        // -v

Run it the way the other generated tables are run:

    python3 tools/gen_settings_fields.py astrolog.h | diff - settingsfields.h
"""

import re
import sys

# type name in astrolog.h -> the tag the table carries
TYPES = {"flag": "f", "int": "i", "long": "l", "real": "r", "char": "c"}

MEMBER = re.compile(
    r"^\s{2}(flag|int|long|real|char)\s+(\*?)([A-Za-z_][A-Za-z0-9_]*)"
    r"(?:\[(\d+)\])?\s*;\s*(?://\s*(.*?)\s*)?$")
SECTION = re.compile(r"^\s{2}//\s+([A-Z][A-Za-z0-9 ]*)$")


def members(lines, first, last):
    """Yield (tag, name, index, section, comment) for one struct body."""
    section = ""
    for line in lines[first:last]:
        m = SECTION.match(line.rstrip("\n"))
        if m:
            section = m.group(1)
            continue
        m = MEMBER.match(line.rstrip("\n"))
        if m is None:
            continue
        base, star, name, count, comment = m.groups()
        tag = "s" if star else TYPES[base]
        comment = comment or ""
        # The trailing comment names the switch, either alone as US
        # writes it ("// -v") or inside prose as GS does ("... (-Xl set).").
        sw = ""
        ms = re.match(r"^(-[A-Za-z0-9~]*)", comment)
        if ms is None:
            ms = re.search(r"\((-[A-Za-z0-9~]+)", comment)
        if ms:
            sw = ms.group(1)
        if count is None:
            yield tag, name, -1, section, sw
        else:
            for i in range(int(count)):
                yield tag, name, i, section, sw


def body(path, opener):
    lines = open(path, encoding="utf-8").read().split("\n")
    first = next(i for i, l in enumerate(lines) if l.startswith(opener)) + 1
    last = next(i for i, l in enumerate(lines) if i > first and
                re.match(r"^\} (US|GS);", l))
    return lines, first, last


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "astrolog.h"
    out = []
    out.append("/*")
    out.append("** GENERATED by tools/gen_settings_fields.py from "
               "astrolog.h -- do not edit.")
    out.append("**")
    out.append("** Every scalar member of US and GS, with the section it "
               "sits under and the")
    out.append("** switch its own comment names. Used by the settings "
               "round trip to ask about")
    out.append("** every field at once rather than one at a time.")
    out.append("*/")
    out.append("")
    out.append("typedef struct _settingfield {")
    out.append("  CONST char *szName;   // \"us.fSidereal\", or "
               "\"us.rgszPath[3]\"")
    out.append("  CONST char *szSect;   // the section comment it sits "
               "under, \"\" if none")
    out.append("  CONST char *szSwitch; // the switch its comment names, "
               "\"\" if none")
    out.append("  short off;            // byte offset within its struct")
    out.append("  char ch;              // f flag, i int, l long, r real, "
               "c char, s char *")
    out.append("  char fGs;             // in GS rather than US")
    out.append("} SETTINGFIELD;")
    out.append("")
    out.append("static CONST SETTINGFIELD rgsetfield[] = {")

    rows = []
    for opener, fGs, pre in (
            ("typedef struct _UserSettings {", 0, "us"),
            ("typedef struct _GraphicsSettings {", 1, "gs")):
        lines, first, last = body(path, opener)
        for tag, name, i, sect, sw in members(lines, first, last):
            if i < 0:
                full = "%s.%s" % (pre, name)
                off = "offsetof(%s, %s)" % ("US" if not fGs else "GS", name)
            else:
                full = "%s.%s[%d]" % (pre, name, i)
                off = "offsetof(%s, %s) + %d * (int)sizeof(char *)" % (
                    "US" if not fGs else "GS", name, i)
            rows.append('  {"%s", "%s", "%s", (short)(%s), \'%s\', %d},'
                        % (full, sect, sw, off, tag, fGs))
    out += rows
    out.append("};")
    out.append("#define csetfield "
               "(int)(sizeof(rgsetfield)/sizeof(SETTINGFIELD))")
    print("\n".join(out))


if __name__ == "__main__":
    main()
