#!/usr/bin/env python3
"""
Translate dialog definitions in astrolog.rc into a C table the Qt build can
lay out directly (see RcBuildDialogQt in qtdialog.cpp).

The point is transcription, not reinterpretation. Windows measures its
dialogs in "dialog units": one horizontal unit is a quarter of the dialog
font's average character width, one vertical unit an eighth of its line
height. Emitting the resource's own x/y/width/height and converting through
that at runtime reproduces the original layout exactly, at whatever font
size the desktop happens to use.

Rebuilding these dialogs out of nested Qt layouts instead -- inferring "two
columns here, a group box there" -- is what made the port look roughly
twice as airy as the original, because every layout level adds its own
margins and spacing.

Usage:  python3 tools/rc2qt.py astrolog.rc > qtrcdlg.h
"""

import re
import sys

# Controls are emitted with the resource symbol they carry, split into a
# prefix and any trailing number -- "deo07" becomes prefix "deo", index 7.
# The Qt side then asks for what it wants by name ("IDOK") or by prefix and
# index ("deo", 7), rather than this script having to know what every
# symbol in the resource means.
SPLIT = re.compile(r"^([A-Za-z_][A-Za-z_0-9]*?)(\d*)$")

KIND = {
    "CONTROL": "ctlCheck", "LTEXT": "ctlLabel", "RTEXT": "ctlLabel",
    "GROUPBOX": "ctlGroup", "PUSHBUTTON": "ctlButton",
    "DEFPUSHBUTTON": "ctlButton", "ICON": "ctlIcon",
    "EDITTEXT": "ctlEdit", "COMBOBOX": "ctlCombo",
}

# The geometry is four consecutive integers, but not reliably at the end of
# the line: CONTROL puts its style flags before them, EDITTEXT and COMBOBOX
# after ("EDITTEXT den01,40,15,40,13,ES_AUTOHSCROLL"). Requiring them at the
# end silently dropped every edit field and combo box in the resource.
INT = re.compile(r"^-?\d+$")
HEAD = re.compile(r"^(dlg\w+)\s+DIALOGEX?\s+\d+,\s*\d+,\s*(\d+),\s*(\d+)")
LINE = re.compile(r"^(%s)\s+(.*)$" % "|".join(KIND))
TEXT = re.compile(r'^"((?:[^"]|"")*)"\s*,\s*([A-Za-z_0-9]+)')
BARE = re.compile(r"^([A-Za-z_0-9]+)\s*,")


def geometry(rest):
    """The first run of four consecutive integer fields, or None."""
    parts = [p.strip() for p in rest.split(",")]
    for i in range(len(parts) - 3):
        run = parts[i:i + 4]
        if all(INT.match(p) for p in run):
            return [int(p) for p in run]
    return None


def controls(body):
    """Yield (kind, text, symbol, x, y, w, h) for each control in a block."""
    for line in body.split("\n"):
        line = line.strip()
        m = LINE.match(line)
        if not m:
            continue
        kind, rest = m.group(1), m.group(2)
        g = geometry(rest)
        if not g:
            continue
        t = TEXT.match(rest)
        if t:
            text, symbol = t.group(1), t.group(2)
        else:
            b = BARE.match(rest)
            text, symbol = "", (b.group(1) if b else "")
        yield KIND[kind], text, symbol, g


def emit(name, w, h, body, out):
    out.append("// %s -- %d x %d dialog units, from astrolog.rc" %
               (name, w, h))
    out.append("static CONST RCCTL rgctl%s[] = {" % name[3:])
    for kind, text, symbol, (x, y, cx, cy) in controls(body):
        m = SPLIT.match(symbol) if symbol else None
        prefix = m.group(1) if m else ""
        index = int(m.group(2)) if (m and m.group(2)) else -1
        text = text.replace('""', '\\"').replace("\\", "\\\\")
        out.append('  {%-10s "%s", "%s", %d, %d,%d,%d,%d},' %
                   (kind + ",", text, prefix, index, x, y, cx, cy))
    out.append("};")
    out.append("#define cctl%s (int)(sizeof(rgctl%s) / sizeof(RCCTL))" %
               (name[3:], name[3:]))
    out.append("#define dx%s %d" % (name[3:], w))
    out.append("#define dy%s %d" % (name[3:], h))
    out.append("")


def main():
    src = open(sys.argv[1], encoding="utf-8", errors="replace",
               newline="").read().replace("\r\n", "\n")
    wanted = sys.argv[2:] or None
    out = ["/*", "** Generated by tools/rc2qt.py from astrolog.rc.",
           "** Do not edit by hand; regenerate instead.", "*/", ""]
    cur = None
    for m in re.finditer(r"^dlg\w+\s+DIALOGEX?[^\n]*\n(?:.*?)^END", src,
                         re.S | re.M):
        block = m.group(0)
        head = HEAD.match(block)
        if not head:
            continue
        name, w, h = head.group(1), int(head.group(2)), int(head.group(3))
        if wanted and name not in wanted:
            continue
        emit(name, w, h, block, out)
    sys.stdout.write("\n".join(out) + "\n")


main()
