#!/usr/bin/env python3
"""
Translate dialog definitions in astrolog.rc into a C table the Qt build can
lay out directly (see RcBuildDialogQt in qtdialog.cpp).

The point is transcription, not reinterpretation. Windows measures its
dialogs in "dialog units": one horizontal unit is a quarter of the dialog
font's average character width, one vertical unit an eighth of its line
height. Emitting the resource's own x/y/width/height and converting through
that at runtime reproduces the original layout exactly, at whatever font
size the desktop happens to use.

Rebuilding these dialogs out of nested Qt layouts instead -- inferring "two
columns here, a group box there" -- is what made the port look roughly
twice as airy as the original, because every layout level adds its own
margins and spacing.

Usage:  python3 tools/rc2qt.py astrolog.rc > qtrcdlg.h
"""

import re
import sys

# Resource control symbol -> the id the Qt side switches on. Checkboxes in
# the object dialogs are dxNN, which maps to object NN-1 and is handled
# separately.
SYMBOL_ID = {
    "IDOK": "butOK",
    "IDCANCEL": "butCancel",
    "dbRe_R0": "butResAll",   "dbRe_R1": "butUnresAll",
    "dbRe_R": "butMinors",    "dbRe_RC": "butCusps",
    "dbRe_Ru": "butUran",     "dbRe_Ry": "butDwarf",
    "dbRT": "butCopy",        "dbRe_YRi": "butRecall",
    "dbSt_RU0": "butResAll",  "dbSt_RU1": "butUnresAll",
    "dbMo_Rm0": "butResAll",  "dbMo_Rm1": "butUnresAll",
    "dbMo_Mar": "butMars",    "dbMo_Jup": "butJupiter",
    "dbMo_Sat": "butSaturn",  "dbMo_Ura": "butUranus",
    "dbMo_Nep": "butNeptune", "dbMo_Plu": "butPluto",
    "dbMo_COB": "butCOB",
}

KIND = {
    "CONTROL": "ctlCheck", "LTEXT": "ctlLabel", "RTEXT": "ctlLabel",
    "GROUPBOX": "ctlGroup", "PUSHBUTTON": "ctlButton",
    "DEFPUSHBUTTON": "ctlButton", "ICON": "ctlIcon",
    "EDITTEXT": "ctlEdit", "COMBOBOX": "ctlCombo",
}

GEOM = re.compile(r"(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+)\s*$")
HEAD = re.compile(r"^(dlg\w+)\s+DIALOGEX?\s+\d+,\s*\d+,\s*(\d+),\s*(\d+)")
LINE = re.compile(r"^(%s)\s+(.*)$" % "|".join(KIND))
TEXT = re.compile(r'^"((?:[^"]|"")*)"\s*,\s*([A-Za-z_0-9]+)')
BARE = re.compile(r"^([A-Za-z_0-9]+)\s*,")


def controls(body):
    """Yield (kind, text, symbol, x, y, w, h) for each control in a block."""
    for line in body.split("\n"):
        line = line.strip()
        m = LINE.match(line)
        if not m:
            continue
        kind, rest = m.group(1), m.group(2)
        g = GEOM.search(rest)
        if not g:
            continue
        t = TEXT.match(rest)
        if t:
            text, symbol = t.group(1), t.group(2)
        else:
            b = BARE.match(rest)
            text, symbol = "", (b.group(1) if b else "")
        yield KIND[kind], text, symbol, [int(v) for v in g.groups()]


def emit(name, w, h, body, out):
    out.append("// %s -- %d x %d dialog units, from astrolog.rc" %
               (name, w, h))
    out.append("static CONST RCCTL rgctl%s[] = {" % name[3:])
    for kind, text, symbol, (x, y, cx, cy) in controls(body):
        idx = re.match(r"^dx[a-z]*(\d+)$", symbol)
        if kind == "ctlCheck" and idx:
            ident = str(int(idx.group(1)) - 1)
        else:
            ident = SYMBOL_ID.get(symbol, "-1")
        text = text.replace('""', '\\"')
        out.append('  {%-10s "%s", %s, %d,%d,%d,%d},' %
                   (kind + ",", text, ident, x, y, cx, cy))
    out.append("};")
    out.append("#define cctl%s (int)(sizeof(rgctl%s) / sizeof(RCCTL))" %
               (name[3:], name[3:]))
    out.append("#define dx%s %d" % (name[3:], w))
    out.append("#define dy%s %d" % (name[3:], h))
    out.append("")


def main():
    src = open(sys.argv[1], encoding="utf-8", errors="replace",
               newline="").read().replace("\r\n", "\n")
    wanted = sys.argv[2:] or None
    out = ["/*", "** Generated by tools/rc2qt.py from astrolog.rc.",
           "** Do not edit by hand; regenerate instead.", "*/", ""]
    cur = None
    for m in re.finditer(r"^dlg\w+\s+DIALOGEX?[^\n]*\n(?:.*?)^END", src,
                         re.S | re.M):
        block = m.group(0)
        head = HEAD.match(block)
        if not head:
            continue
        name, w, h = head.group(1), int(head.group(2)), int(head.group(3))
        if wanted and name not in wanted:
            continue
        emit(name, w, h, block, out)
    sys.stdout.write("\n".join(out) + "\n")


main()
