#!/usr/bin/env python3
"""Emit the menu bar's accelerator column, exactly as astrolog.rc writes it.

    python3 tools/rc_accel.py astrolog.rc > qtrcaccel.h

Windows draws the text after the "\\t" in each MENUITEM verbatim, so a
command bound to Shift+V shows as "V" and one bound to Alt+Shift+O shows
as "Alt+O" -- the resource spells a shifted letter by capitalising it.
Qt derives that column from the QKeySequence instead and spells the
modifier out, giving "Shift+V" and "Alt+Shift+O": the same keys in a
different notation, on every menu, every time. Carrying the resource's own
string across removes the difference at the source.

Only the menu bar block is read, not the context menu popups further down
the file: two labels appear in both with different keys there, and the
menu bar is what this table is applied to.
"""
import re
import sys


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "astrolog.rc"
    with open(path) as f:
        lines = f.read().splitlines()

    # The menu bar is the first "MENU" block; the next one starts the
    # context menus.
    start = next(i for i, l in enumerate(lines) if re.match(r'^menu MENU\b', l))
    end = next(i for i, l in enumerate(lines)
               if i > start and re.match(r'^\w+ MENU\b', l))
    block = "\n".join(lines[start:end])

    seen, out = {}, []
    for m in re.finditer(r'MENUITEM\s+"([^"]*)"', block):
        text = m.group(1)
        if '\\t' not in text:
            continue
        label, accel = text.split('\\t', 1)
        # The 96 macro entries are built at runtime and renamed by "-WM",
        # so a fixed label cannot find them -- and their column is a plain
        # function key, which Qt already spells the way Windows does.
        if re.match(r'^&?M&?a&?c&?r&?o&? ', label):
            continue
        if label in seen:
            if seen[label] != accel:
                sys.exit("conflicting accelerator text for %r: %r vs %r"
                         % (label, seen[label], accel))
            continue
        seen[label] = accel
        out.append((label, accel))

    w = max(len(l) for l, _ in out) + 3
    print("// Generated by tools/rc_accel.py from astrolog.rc -- do not edit.")
    print("// The accelerator column as Windows draws it, keyed by menu label.")
    print("")
    print("typedef struct _RcAccel { CONST char *szLabel, *szAccel; } RCACCEL;")
    print("")
    print("CONST RCACCEL rgaccelQt[] = {")
    for label, accel in out:
        print('  {%-*s "%s"},' % (w, '"%s",' % label, accel))
    print("};")
    print("CONST int caccelQt = %d;" % len(out))


main()
