#!/usr/bin/env python3
"""Emit the menu bar's label-to-command-id map from astrolog.rc.

    python3 tools/rc_cmd.py astrolog.rc resource.h > qtrccmd.h

Windows routes every menu choice through one WM_COMMAND switch, so it has
a numeric command id in hand and can let an AstroExpression ("-~WQ",
us.szExpMenu) rewrite it before dispatching. This port binds each action
to its own handler by label and never had an id, which is why that hook
was unimplemented. This table supplies the missing half.
"""
import re
import sys


def main():
    rcpath = sys.argv[1] if len(sys.argv) > 1 else "astrolog.rc"
    hpath = sys.argv[2] if len(sys.argv) > 2 else "resource.h"
    with open(rcpath, newline='') as f:
        lines = f.read().split('\r\n')
    with open(hpath, newline='') as f:
        vals = dict(re.findall(r'#define\s+(cmd\w+)\s+(\d+)', f.read()))

    start = next(i for i, l in enumerate(lines) if re.match(r'^menu MENU\b', l))
    end = next(i for i, l in enumerate(lines)
               if i > start and re.match(r'^\w+ MENU\b', l))

    seen, out = set(), []
    for l in lines[start:end]:
        m = re.match(r'\s*MENUITEM\s+"([^"]*)"\s*,\s*(cmd\w+)', l)
        if not m:
            continue
        label, cmd = m.group(1).split('\\t')[0], m.group(2)
        if cmd not in vals:
            sys.exit("no numeric value for %s" % cmd)
        # A label can name the same command from two menus; keep the first.
        if label in seen:
            continue
        seen.add(label)
        out.append((label, cmd, vals[cmd]))

    w = max(len(l) for l, _, _ in out) + 3
    print("// Generated by tools/rc_cmd.py from astrolog.rc -- do not edit.")
    print("// Menu label to Windows command id, so an AstroExpression can be")
    print("// handed the same number Windows hands it.")
    print("")
    print("typedef struct _RcCmd { CONST char *szLabel; int cmd; } RCCMD;")
    print("")
    print("CONST RCCMD rgcmdQt[] = {")
    for label, cmd, val in out:
        print('  {%-*s %s},  // %s' % (w, '"%s",' % label, val, cmd))
    print("};")
    print("CONST int ccmdQt = %d;" % len(out))


main()
