#!/usr/bin/env python3
"""seorbel.txt -> ephpromelem.h: every element set in the stock Swiss
Ephemeris seorbel.txt, as a compiled table the Prometheia source hands to
prometheia_calc_elements().

    python3 tools/seorbel2prom.py seorbel.txt > ephpromelem.h
    python3 tools/seorbel2prom.py seorbel.txt | diff - ephpromelem.h   # check

The input is upstream's file (aloistr/swisseph master, ephe/seorbel.txt),
byte-identical to this tree's copy since 2026-09-29. Since 2026-09-30 this
table is only the FALLBACK: the Prometheia source reads the first seorbel.txt
on the search path Swiss was handed, as Swiss does (ephprom.cpp,
PeEphPromElem), and uses these stock sets where there is none or the file
cannot be followed. The reader's grammar is this file's, and the suite
requires the two to agree exactly on the stock file.

A set is one non-comment line: epoch, equinox, mean anomaly, semi-major
axis, eccentricity, argument of perihelion, ascending node, inclination,
name, and an optional "geo" for an Earth-centred orbit. Each numeric field
is a polynomial in T, "c0 + c1 * T + c2 * T2 ...". Epoch and equinox may be
J1900, B1950, J2000 or a Julian day; the equinox may also be JDATE, the
equinox of date.
"""
import re
import sys

EPOCHS = {"J1900": 2415020.0, "B1950": 2433282.42345905, "J2000": 2451545.0}
EQ_J2000, EQ_B1950, EQ_J1900, EQ_OFDATE, EQ_EXPLICIT = 0, 1, 2, 3, 4
NTERMS = 5


def poly(field):
    """'252.8987988 + 707550.7341 * T' -> [252.8987988, 707550.7341]."""
    s = field.replace(" ", "")
    c = [0.0] * NTERMS
    for sign, num, t in re.findall(r"([+-]?)([0-9.]+(?:[eE][+-]?\d+)?)(\*T\d?)?", s):
        v = float(num) * (-1.0 if sign == "-" else 1.0)
        p = 0 if not t else (1 if t == "*T" else int(t[2:]))
        c[p] += v
    return c


def epoch(field):
    f = field.strip()
    return EPOCHS[f] if f in EPOCHS else float(f)


def equinox(field):
    f = field.strip()
    if f == "JDATE":
        return EQ_OFDATE, 0.0
    if f == "J2000":
        return EQ_J2000, 0.0
    if f == "B1950":
        return EQ_B1950, 0.0
    if f == "J1900":
        return EQ_J1900, 0.0
    return EQ_EXPLICIT, float(f)


def sets(text):
    for line in text.splitlines():
        body = line.strip()
        if not body or body.startswith("#"):
            continue
        body = body.split("#", 1)[0]
        f = [x.strip() for x in body.split(",")]
        geo = len(f) > 9 and f[9].lower() == "geo"
        eq, eqjd = equinox(f[1])
        yield {"epoch": epoch(f[0]), "eq": eq, "eqjd": eqjd,
               "geo": geo, "name": f[8],
               "el": [poly(f[k]) for k in range(2, 8)]}


def main():
    text = open(sys.argv[1], encoding="utf-8", errors="replace").read()
    rows = list(sets(text))
    out = ["// ephpromelem.h -- GENERATED by tools/seorbel2prom.py from the stock",
           "// seorbel.txt; do not edit. Every element set in file order, so index i",
           "// is Swiss's fictitious body SE_FICT_OFFSET + i. Coefficients of T^0..T^4",
           "// per element: mean anomaly (deg), semi-major axis (AU), eccentricity,",
           "// argument of perihelion (deg), ascending node (deg), inclination (deg).",
           "",
           "#ifndef EPHPROMELEM_H",
           "#define EPHPROMELEM_H",
           "",
           "typedef struct _ephpromelem {",
           "  double epoch;        // JD TT",
           "  int equinox;         // eph::Equinox / PROMETHEIA_EQUINOX_*",
           "  double equinoxJd;    // explicit equinox, else 0",
           "  int centre;          // 0 Sun, 1 Earth",
           "  double el[6][5];",
           "  const char *szName;",
           "} EPHPROMELEM;",
           "",
           "static const EPHPROMELEM rgEphPromElem[] = {"]
    for r in rows:
        els = ", ".join("{" + ", ".join(repr(v) for v in e) + "}" for e in r["el"])
        name = r["name"].encode("ascii", "replace").decode().replace('"', "'")
        out.append("  {%r, %d, %r, %d, {%s}, \"%s\"}," %
                   (r["epoch"], r["eq"], r["eqjd"], 1 if r["geo"] else 0, els, name))
    out += ["};",
            "#define cEphPromElem ((int)(sizeof(rgEphPromElem) / sizeof(rgEphPromElem[0])))",
            "",
            "#endif // EPHPROMELEM_H", ""]
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
